### ISSUE TITLE
[BUG] Trakt and RD settings deleted randomly need to authorize both again and again

### ISSUE THREAD

**Issue by confever** [nixgates/plugin.video.seren#635] opened 2021-06-21 10:44 UTC
**Describe the bug**
I need to constantly enter trakt and rd again after a few hours randomly. nned to authorize again
check the settings menu and the settings on the accounts tab is deleted

**To Reproduce**
1. Go to 'settings
2. Click on 'account
3. Scroll down to 'trakt and rd settings'

**Expected behavior**
the settings for rd and trakt shouldn't auto deleted

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [19.1
 - seren version 2.1.1
 - repo version 2.0.2

**Additional context**

![image](https://user-images.githubusercontent.com/53037415/122749806-f66b3000-d2b7-11eb-8aba-72b5e3003d33.png)

![image](https://user-images.githubusercontent.com/53037415/122749986-2adeec00-d2b8-11eb-8f8e-cff79d199c7e.png)

![image](https://user-images.githubusercontent.com/53037415/122750068-4649f700-d2b8-11eb-982a-46d0ffb37543.png)

![image](https://user-images.githubusercontent.com/53037415/122750109-5366e600-d2b8-11eb-9f93-93a80685db68.png)

**Comment by drinfernoo** [comment] 2021-06-21 12:16
Please attach a debug log

**Comment by drinfernoo** [comment] 2021-06-23 14:33
There's not really anything Seren does that may have made this happen, but our settings code has been reworked again just to double check... so we'll see how it goes for next update.

**Comment by dplim87** [comment] 2021-06-24 14:36
Unsure of RD, but I've had this issue with Trakt since the 2.1.1 update, likely related to the changes made referenced in the changelog.
> Improve AUTH refresh flow edge case coverage for Trakt and TVDB

Was going to try tracking this down myself when I got the time, but perhaps someone more familiar with the changes made could find it faster.
<details><summary>Related Error</summary>

> 2021-06-24 10:02:40.600 T:5346     INFO <general>: SEREN (1): Seren, Running Path - {'action': 'showsNextUp', 'from_widget': 'true'}
> 2021-06-24 10:02:42.194 T:5346     INFO <general>: SEREN (1): Trakt Token requires refreshing...
> 2021-06-24 10:02:42.263 T:5346    ERROR <general>: SEREN (1): Connection Error to Trakt: (<resources.lib.indexers.trakt.TraktAPI object at 0xd65a42b0>, '/oauth/token', {'refresh_token': '#####', 'client_id': '#####', 'client_secret': '#####', 'redirect_uri': 'urn:ietf:wg:oauth:2.0:oob', 'grant_type': 'refresh_token'}) - {}
> 2021-06-24 10:02:42.263 T:5346    ERROR <general>: SEREN (1): 'TraktAPI' object has no attribute 'session'
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>: Exception ignored in: 
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>: <function TraktAPI.__del__ at 0xd65b7140>
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>: 
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>: Traceback (most recent call last):
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 386, in __del__
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>:     
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: self.session.close()
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: 
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: AttributeError
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: : 
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: 'TraktAPI' object has no attribute 'session'
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: 
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>     Error Type: <class 'AttributeError'>
>     Error Contents: 'TraktAPI' object has no attribute 'session'
> 	Traceback (most recent call last):
> 	File "/storage/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
> 	router.dispatch(g.REQUEST_PARAMS)
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 449, in dispatch
> 	tvshowMenus.Menus().my_next_up()
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 20, in __init__
> 	self.trakt = TraktAPI()
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 198, in __init__
> 	self.try_refresh_token()
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 557, in try_refresh_token
> 	response = self.post(
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 117, in wrapper
> 	response = func(*args, **kwargs)
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 755, in post
> 	return self.session.post(
> 	AttributeError: 'TraktAPI' object has no attribute 'session'
> 	-->End of Python script error report<--
> 2021-06-24 10:02:43.942 T:5346     INFO <general>: Python interpreter stopped
</details>

**Comment by dplim87** [comment] 2021-06-24 15:16
I believe this is related to the clientid and secret being written to settings as blank. Perhaps the new settings code needs some tweaking? After manually editing the settings.xml to add the clientid and secret, it appears to be working.
<details><summary>Related Error</summary>

> 2021-06-24 10:02:40.600 T:5346     INFO <general>: SEREN (1): Seren, Running Path - {'action': 'showsNextUp', 'from_widget': 'true'}
> 2021-06-24 10:02:42.194 T:5346     INFO <general>: SEREN (1): Trakt Token requires refreshing...
> 2021-06-24 10:02:42.263 T:5346    ERROR <general>: SEREN (1): Connection Error to Trakt: (<resources.lib.indexers.trakt.TraktAPI object at 0xd65a42b0>, '/oauth/token', {'refresh_token': '#####', 'client_id': '#####', 'client_secret': '#####', 'redirect_uri': 'urn:ietf:wg:oauth:2.0:oob', 'grant_type': 'refresh_token'}) - {}
> 2021-06-24 10:02:42.263 T:5346    ERROR <general>: SEREN (1): 'TraktAPI' object has no attribute 'session'
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>: Exception ignored in: 
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>: <function TraktAPI.__del__ at 0xd65b7140>
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>: 
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>: Traceback (most recent call last):
> 2021-06-24 10:02:42.315 T:5346    ERROR <general>:   File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 386, in __del__
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>:     
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: self.session.close()
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: 
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: AttributeError
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: : 
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: 'TraktAPI' object has no attribute 'session'
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: 
> 2021-06-24 10:02:42.321 T:5346    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>     Error Type: <class 'AttributeError'>
>     Error Contents: 'TraktAPI' object has no attribute 'session'
> 	Traceback (most recent call last):
> 	File "/storage/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
> 	router.dispatch(g.REQUEST_PARAMS)
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 449, in dispatch
> 	tvshowMenus.Menus().my_next_up()
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 20, in __init__
> 	self.trakt = TraktAPI()
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 198, in __init__
> 	self.try_refresh_token()
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 557, in try_refresh_token
> 	response = self.post(
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 117, in wrapper
> 	response = func(*args, **kwargs)
> 	File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 755, in post
> 	return self.session.post(
> 	AttributeError: 'TraktAPI' object has no attribute 'session'
> 	-->End of Python script error report<--
> 2021-06-24 10:02:43.942 T:5346     INFO <general>: Python interpreter stopped
</details>

**Comment by thebatfink** [comment] 2021-06-26 23:21
Happens constantly for me and other posts on reddit around for same issue where auth is seemingly lost at random.

**Comment by dplim87** [comment] 2021-06-26 23:45
I made a post, but had removed it. I believe it's some kinks that was to be
worked out in the new settings code they pushed out. I'm sure they'll get
it fixed soon. But I manually edited the
profile/user_data/addon_data/plugin.video.seren/settings.xml
Adding the default clientid and secret to trakt.clientid and trakt.secret
keys respectively in there and then restarting Kodi has stopped the issue
from occuring anymore for me so far.

Sincerely,
David Plimley

**Comment by dplim87** [comment] 2021-06-26 23:56
I made a post before but had removed it. I believe it's some kinks that have to be
worked out in the new settings code that was pushed out (although I could be wrong). I'm sure they'll get
it fixed soon. But, I manually edited the
profile/user_data/addon_data/plugin.video.seren/settings.xml file.
Adding the default clientid and secret to trakt.clientid and trakt.secret
keys respectively in there and then restarting Kodi has stopped the issue
from occuring anymore for me so far with Trakt. I do not use RD, so I could not confirm if that would also work.

**Comment by thebatfink** [comment] 2021-06-27 09:39
He posted on reddit will be fixed in next version at weekend and a workaround. I guess was able to reproduce in the end. Thanks.

**Comment by cphilpotts** [comment] 2021-06-28 23:10
This is also happening to me. Every couple hours I need to re-enter my real debrid authentication and change my settings back. 

Here’s my log:

https://paste.kodi.tv/cefakiwexe

**Comment by drinfernoo** [comment] 2021-06-28 23:32
https://redd.it/o8ppa5

**Comment by cphilpotts** [comment] 2021-06-28 23:55
> https://redd.it/o8ppa5

Even after doing this, my “Next Up Sort Style” setting keeps resetting back to “Release Date” after I switch it to “Recently Watched”

**Comment by cphilpotts** [comment] 2021-06-29 00:49
> > https://redd.it/o8ppa5
> 
> Even after doing this, my “Next Up Sort Style” setting keeps resetting back to “Release Date” after I switch it to “Recently Watched”

All my API keys are also being removed. Will these settings issue be fixed with the next update?

**Comment by drinfernoo** [comment] 2021-06-29 01:34
@cphilpotts We have been unable to reproduce that issue, but have made a few changes that may help those who are experiencing it. We'll have to see once the next version comes out.

**Comment by Nuklear92** [comment] 2021-06-30 13:05
Even though I read most of the comments here and I seen that it should be fixed by next update. I wanted to also point out that in my experience since two days ago. I also been experiencing some settings being randomly reset to default after being modified. Also, I'd experience the Trakt and RD Auths being also deleted and having to re enter them 1 time. All of this after a fresh install of Kodi and Seren which leads me to believe that it wasn't a faulty Seren installation I had previously.

This is definitely an odd bug/issue and it's quite hard to reproduce and document it. It just happens randomly out of nowhere after certain periods of time. 🤷‍♂️

**Comment by drinfernoo** [comment] 2021-07-02 02:13
This has been a very hard bug to track down... and is still labeled "Unreproducible" for that very reason. We haven't been able to reproduce it. With that in mind, the settings code has had a nice rework for 2.1.2, so we're hoping this one won't crop up again. In any case, I'm going to close it now, and if it comes up again, we'll address it then.

**Closed by drinfernoo** 2021-07-02 02:13 UTC
Labels: Unreproducible, awaiting update, bug

**Comment by cphilpotts** [comment] 2021-07-02 13:42
> This has been a very hard bug to track down... and is still labeled "Unreproducible" for that very reason. We haven't been able to reproduce it. With that in mind, the settings code has had a nice rework for 2.1.2, so we're hoping this one won't crop up again. In any case, I'm going to close it now, and if it comes up again, we'll address it then.

So far so good. Fingers crossed it holds.

**Comment by cphilpotts** [comment] 2021-07-02 14:39
> This has been a very hard bug to track down... and is still labeled "Unreproducible" for that very reason. We haven't been able to reproduce it. With that in mind, the settings code has had a nice rework for 2.1.2, so we're hoping this one won't crop up again. In any case, I'm going to close it now, and if it comes up again, we'll address it then.

Settings for Sort Order and API keys reset after less than an hour. Not sure what's triggering it to clear.

**Comment by cphilpotts** [comment] 2021-07-05 19:32
> This has been a very hard bug to track down... and is still labeled "Unreproducible" for that very reason. We haven't been able to reproduce it. With that in mind, the settings code has had a nice rework for 2.1.2, so we're hoping this one won't crop up again. In any case, I'm going to close it now, and if it comes up again, we'll address it then.

This has started happening again in 2.1.2. RD won't stay authorized and changes to "invalid" in settings before I've finished watching a show. I've wiped add-on data, uninstalled and reinstalled twice now.
