### ISSUE TITLE
[BUG] Unable to get to Episodes via Seren on anything in my Library

### ISSUE THREAD

**Issue by ThePapaw** [nixgates/plugin.video.seren#651] opened 2021-07-16 16:05 UTC
**Describe the bug**
If something from my Trakt collection is has been added to my library (either local downloaded files or other addons),  Seren will not display the episodes. It finds my collection, shows the "Seasons", but errors after that. Works fine in other TV Shows that are not in my library.

**To Reproduce**
1. Go to 'My Shows'
2. Click on 'Collection'
3. Pick any show that is in my library
4. Pick any season and I get an error

**Expected behavior**
Show the episodes in that season.

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [18.9 (my fork) running on 3 different Nvidea Shields
Download shows and other addon data are stored on NAS

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6831967/kodi.log)

**Additional context**
The same happens if I search for a show that is already in my library. This has been happening with the last 2 releases. I have "Wiped" addon; deleted the userdata/addon_data/plugin.video.seren folder. Revoked Trackt, re-authorized, etc..

**Comment by drinfernoo** [comment] 2021-07-16 16:13
This may be due to a bug we've already identified with specials... Could you make sure that "Hide Specials" is enabled, and then rebuild the Trakt DB, to see if that helps?

Also, could you give examples of what shows this is happening with?

**Comment by ThePapaw** [comment] 2021-07-16 18:29
@drinfernoo Thank you much, "Hide Specials" got it going again. It was happening in every show that I have added to my TV Show Library. Didn't matter if it was physical files or stream files from another 3rd party addon. If it was added to the TV Library, it caused the error until I did what you suggested. Thank you much, it was driving me nuts...lol

**Comment by drinfernoo** [comment] 2021-07-16 20:17
The fact they were in your library is inconsequential, since Seren does no interfacing with Kodi's library... and isn't really helpful in figuring out which shows are causing issues, since I don't know what shows are in your library 😅

**Comment by ThePapaw** [comment] 2021-07-16 20:32
I am doubtful it is specific to a certain tv show, as there are 170+ shows in the library on the kodi instance I am am tinkering with. In the log I provided earlier, I created the error with 2 shows that had been added to the library. Not sure what else I might be able to provide that could assist ya. More than happy to help. The shows were from old things like Little Rascals, 100's of cartoons like looney tunes & disney shorts, m*a*s*h*, dateline, hercules, xena, green acres, etc.. (stored locally on NAS). Also shows that were added to the library like Deadliest Catch, Mountain Men, Loki, (files created by the addon also saves on NAS)

**Comment by drinfernoo** [comment] 2021-07-16 21:36
> I am doubtful it is specific to a certain tv show, as there are 170+ shows in the library on the kodi instance I am am tinkering with. In the log I provided earlier, I created the error with 2 shows that had been added to the library. Not sure what else I might be able to provide that could assist ya. More than happy to help. The shows were from old things like Little Rascals, 100's of cartoons like looney tunes & disney shorts, m_a_s_h_, dateline, hercules, xena, green acres, etc.. (stored locally on NAS). Also shows that were added to the library like Deadliest Catch, Mountain Men, Loki, (files created by the addon also saves on NAS)

For what it's worth, in the case of the other user who helped us find the bug I mentioned (#628), we narrowed down that his issue was with a **specific** show ([Street Outlaws: New Orleans](https://trakt.tv/shows/street-outlaws-new-orleans)), which has *two* "Specials" seasons listed on Trakt.tv... which is highly unusual, and is **not** something Seren's Trakt DB was designed to handle properly, as it's very rare to run into that case. None of us have ever seen it except for with this one show. A fix is coming for it, hopefully in the next update, but his error looked exactly like the one in your log, and had the same symptoms.

If you can think of any show in your Trakt Collection (not specifically in your Kodi library) that has a weird set of seasons, or particularly with specials, that could be the culprit, as *even one* show like this can cause the Trakt DB to get out of whack.

**Comment by drinfernoo** [comment] 2021-08-05 13:26
This one should now be fixed in 2.1.4. Would you attempt a database rebuild, and confirm if it's working for you now?

**Comment by ThePapaw** [comment] 2021-08-05 18:47
> This one should now be fixed in 2.1.4. Would you attempt a database rebuild, and confirm if it's working for you now?

This appears to be working for me now. Just curious, is Seren suppose to sync Trakt every 10 minutes or so?

**Comment by drinfernoo** [comment] 2021-08-05 18:50
Seren's background sync runs every 13-17 minutes.

**Closed** 2021-08-05 18:50 UTC
Labels: bug
