### ISSUE TITLE
[BUG] Seren 2.1.1 some TV shows won't populate episodes so it can't play them

### ISSUE THREAD

**Issue by Liquidrag** [nixgates/plugin.video.seren#628] opened 2021-06-19 15:17 UTC
**Describe the bug**

When clicking on some tv shows, I get an error and 0 episodes populate. I first noticed it on Riverdale.

**To Reproduce**
1. Go to 'Discover TV shows> Most popular'
2. Click on ’TWD, Sherlock, HIMYM, Friends, Stranger Things'
3. No episodes show up but the seasons are still there.

**Expected behavior**
Clicking on a show should pull up the show and its seasons and episodes. Some shows work as expected like GoT and Breaking Bad.

**Screenshots**
![1](https://user-images.githubusercontent.com/43726430/122646782-a1c48b00-d0e6-11eb-8857-6c827ad86a57.jpg)
![2](https://user-images.githubusercontent.com/43726430/122646784-a426e500-d0e6-11eb-9974-1144ae6b9348.jpg)
![3](https://user-images.githubusercontent.com/43726430/122646786-a5581200-d0e6-11eb-8472-ceb05b1c9271.jpg)
![4](https://user-images.githubusercontent.com/43726430/122646788-a5f0a880-d0e6-11eb-9ff0-3a5bc05636bf.jpg)
![5](https://user-images.githubusercontent.com/43726430/122646789-a5f0a880-d0e6-11eb-92c5-8ab374e0cd5f.jpg)
![6](https://user-images.githubusercontent.com/43726430/122646791-a6893f00-d0e6-11eb-9e03-8a2cb2c1bd45.jpg)
![7](https://user-images.githubusercontent.com/43726430/122646792-a6893f00-d0e6-11eb-8258-e6a11fdd8554.jpg)
![8](https://user-images.githubusercontent.com/43726430/122646793-a721d580-d0e6-11eb-8c2f-d23f6c96192d.jpg)

**Kodi Version (please complete the following information):**
 - Kodi Version 19.1
 - Seren 2.1.1
 - OSX BigSur

**Additional context**
I have cleared cache, torrent cache, completely uninstalled seren, rebooted my Mac, reinstalled seren, rebuilt my database and this still happens. Here's a screenshot of the latest error and the full log.
<img width="2560" alt="Screen Shot 2021-06-19 at 10 15 13 AM" src="https://user-images.githubusercontent.com/43726430/122646925-4d6ddb00-d0e7-11eb-8eea-4186d858994e.png">
https://paste.kodi.tv/mamanobixe.kodi

**Comment by drinfernoo** [comment] 2021-06-19 23:56
Can you get a *debug* log?

**Comment by Liquidrag** [comment] 2021-06-20 00:31
> Can you get a _debug_ log?

I hope I did this right.
https://paste.kodi.tv/axukijipoh.kodi

**Comment by drinfernoo** [comment] 2021-06-20 00:38
Hmm... Are these by any chance shows that you've entered into from an AutoWidget widget? If so, do you have the same issue by navigating directly to them within Seren?

**Comment by Liquidrag** [comment] 2021-06-20 01:08
> Hmm... Are these by any chance shows that you've entered into from an AutoWidget widget? If so, do you have the same issue by navigating directly to them within Seren?

All but Riverdale were accessed within Seren, Riverdale was accessed through a widget pointing to Seren's Next up.

**Comment by bdkbaik** [comment] 2021-06-20 17:16
Hi, I also encounter same issue where the infinite movie cannot be selected

**Comment by drinfernoo** [comment] 2021-06-21 00:54
@bdkbaik Do you have "Hide unaired items" enabled? If so, uncheck it. "Infinite" is considered unaired at this point.

**Comment by bdkbaik** [comment] 2021-06-21 05:16
@drinfernoo it's working, sorry about that

**Comment by drinfernoo** [comment] 2021-06-21 14:56
@Liquidrag, can you (in Seren settings) clear cache, then rebuild your Trakt database. Make sure to allow Trakt to finish rebuilding (make sure to wait for the notification indicating as such).

Then try again.

**Comment by Liquidrag** [comment] 2021-06-21 16:12
> @Liquidrag, can you (in Seren settings) clear cache, then rebuild your Trakt database. Make sure to allow Trakt to finish rebuilding (make sure to wait for the notification indicating as such).
> 
> Then try again.

Tried that too but no dice. I decided to do a fresh install of Kodi and only put Seren on to test and it still gave me the error so I uninstalled kodi and tried again and now it seems to be working fine. thank you @drinfernoo for putting in the time to help me. Now I'm off to rebuild my build.

**Comment by drinfernoo** [comment] 2021-06-21 16:53
So are you saying this is no longer reproducible? You no longer have the issue?

**Comment by Liquidrag** [comment] 2021-06-21 19:54
> So are you saying this is no longer reproducible? You no longer have the issue?

Yessir, we can close this.

**Comment by drinfernoo** [comment] 2021-06-26 13:58
@Liquidrag, are you saying you're having this issue again? I'll need a new full debug log. We were never able to reproduce it.

**Comment by Liquidrag** [comment] 2021-06-27 15:48
> @Liquidrag, are you saying you're having this issue again? I'll need a new full debug log. We were never able to reproduce it.

Yes I'm sorry to say the issue popped up again. I have installed tried on a fresh install of kodi, installed seren, paired trakt, and ran into the same issues. Afterwards I unpaired trakt and the episodes show as expected, so I think it has something to do with the way trakt is building/rebuilding the database. Here is the debug log and if you want, I can send you this build on tg.

https://paste.ubuntu.com/p/zz6mXw8P2C/

**Comment by drinfernoo** [comment] 2021-07-02 02:26
I believe this should be fixed as of 2.1.2. Make sure that you allow the Trakt database sync to fully complete.

**Comment by Liquidrag** [comment] 2021-07-03 03:19
> I believe this should be fixed as of 2.1.2. Make sure that you allow the Trakt database sync to fully complete.

Sorry to say it still is happening. Fresh install of kodi 19.1, Seren 2.1.2, click on TV>Most popular and all episodes populate, but then I go in settings and auth trakt, let the database sync/rebuild for a few hours just to make sure its finished, go back into TV>Most popular and a good handful of shows throws up an error when clicking in seasons.

**Comment by drinfernoo** [comment] 2021-07-03 03:42
The sync only take a couple.minutes maximum, there's no need to let it build for "a few hours".

I can't say that I've seen anything like that happen. Can you get a nice new debug log (if there are actual errors)?

**Comment by Liquidrag** [comment] 2021-07-03 04:40
> The sync only take a couple.minutes maximum, there's no need to let it build for "a few hours".
> 
> I can't say that I've seen anything like that happen. Can you get a nice new debug log (if there are actual errors)?

It has never taken that long before but I just let it run that long just to make sure. I can't say since I had this issue that I have seen it say it completed building the database. Here is a new log, please lmk if I did it correctly. https://paste.ubuntu.com/p/ccQHgBcBxS/

**Comment by drinfernoo** [comment] 2021-07-03 14:00
Do you have "Hide Specials", "Hide Watched Items", or "Hide Unaired Items" turned on?

Also, could you try to get a *debug* log of your Trakt rebuild? It seems something's going wrong there.

**Comment by Liquidrag** [comment] 2021-07-03 16:48
I have "Hide unaired" checked.  Is there another place I can use to paste the error? It keeps erroring out because it is too big.

**Comment by drinfernoo** [comment] 2021-07-16 21:38
We narrowed down that this issue is caused by a **specific** show ([Street Outlaws: New Orleans](https://trakt.tv/shows/street-outlaws-new-orleans)), which has *two* "Specials" seasons listed on Trakt.tv... which is highly unusual, and is **not** something Seren's Trakt DB was designed to handle properly, as it's very rare to run into that case. None of us have ever seen it except for with this one show. A fix is coming for it, hopefully in the next update :+1:

As a workaround, turning on "Hide Specials" and/or removing that show (or any others with "weird" seasons like that) from your Collection should work.

**Comment by Liquidrag** [comment] 2021-07-18 13:28
Wonderful! Thank you guys again!

**Comment by drinfernoo** [comment] 2021-08-05 13:27
This one should now be fixed in 2.1.4. Would you attempt a database rebuild, and confirm if it's working for you now?

**Comment by Liquidrag** [comment] 2021-08-07 22:37
> This one should now be fixed in 2.1.4. Would you attempt a database rebuild, and confirm if it's working for you now?

Should I add Street Outlaws:NO again and test? Right now it never completes building the db.

**Comment by drinfernoo** [comment] 2021-08-07 23:38
It should definitely be working without that show... is it not working even without that show?

**Comment by Liquidrag** [comment] 2021-08-08 00:21
> It should definitely be working without that show... is it not working even without that show?

Everything is working as it should without the show and specials turned off, but with the new update, the rebuilding db never completes.

**Comment by drinfernoo** [comment] 2021-10-03 14:26
This should be fixed in 2.1.5, can you check?

**Comment by Liquidrag** [comment] 2021-10-05 17:53
> This should be fixed in 2.1.5, can you check?

Db looks like it built properly after readding that show. I’ll continue testing and will update if I run into this again. Thank you guys.

**Closed** 2021-11-16 15:20 UTC
Labels: bug
