### ISSUE TITLE
[REQUEST] Easynews Support

### ISSUE THREAD

**Issue by somexone** [nixgates/plugin.video.seren#530] opened 2021-02-19 00:36 UTC
Add support for Easynews.

I absolutely love Seren and it's my main add on. However I have to use a second add on cause I am a huge Easynews user. I'd love Easynews support so I would only have to ever use Seren.

**Comment by drinfernoo** [comment] 2021-02-19 01:44
Duplicate of #24.

**Closed by drinfernoo** 2021-02-19 01:44 UTC
Labels: enhancement
