### ISSUE TITLE
Next up list not refreshing after episode watched

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#68] opened 2019-02-28 14:11 UTC
When you have watched an episode in Up Next and close the episode you are presented with the up next list section again to select another episode.

The list is not being refreshed / updated to show the next episode as soon as you click close on the current playing episode.

You have to exit out of next up and load the list again for it refresh.

**Comment by SerpentDrago** [comment] 2019-02-28 14:29
you do have Up next configured to "do nothing " if you don't click next right ? as per seren configuration instructions

**Comment by lukehansford** [comment] 2019-02-28 21:26
This is happening even without the Up Next addon enabled. It used to show a blue loading circle after you stopped / closed the episode you just finished watching and the Up Next list would update to show the next episode in the list or remove the episode you just watched if no next episode exists.

I just done a fresh install of Kodi 18.1 stable the latest version and installed Kodi with default settings. The list is still not refreshing after you have watched an episode.

If you exit out of the Up Next list and re enter it displays a tick next to the episode you just watched and has not refreshed the list either. 

When you watch any episode even one where there is no next episode to play next it has stopped refreshing the list after you exit the episode and are brought back to the Up Next list under the My Shows section. it just shows a tick next to the episode you just watched. 

Realizer also had this issue that the Dev fixed a few weeks ago.

Exiting out of the Up Next section is also not refreshing the list.

Only clearing the cache under tools and the re loading the Up Next section is forcing a refresh.

Seems it got broken in one of the last updates.

I have also just tried it with the UP next enabled and set the up next add-on to do nothing and clicked close on an episode and exit the currently finished and playing episode. When you exit the episode it shows the up next section again with a tick next to the episode you just watched. It used to update the list to show the next episode or remove the one you just watched if no next episode is available.

**Comment by nixgates** [comment] 2019-03-01 03:27
Please note: Up Next is a seperate addon to Seren and Next Up is a menu item inside Seren.
(Now that we got that all cleared up)

This can be fixed by requesting a refresh on the current Kodi container after a items finishes playing but this will occur on any menu list including if you traverse to another addon whilst playing something (ie: the new menu location you are on will be refreshed)

**Comment by lukehansford** [comment] 2019-03-01 12:29
Sorry for the confusion.

Can you make it refresh the Next Up list when an episode has been watched in a future update or give us the option to turn it on in the settings

I thought a few updates before Seren was refreshing the Next Up list and it got broken in recent updates?

Realizer and a few other add-ons do this for the Trakt progress list.

**Comment by nixgates** [comment] 2019-03-01 12:43
Yea it's cool, it's not that it can't be done, it's just a matter changing a few things.
I'll look into it and let you know.

**Comment by lukehansford** [comment] 2019-03-01 14:29
I am having a big issue on Kodi 18.1.

After an episode is watched in Next Up list it is placing a tick next to the episode and it is stuck like this. It is marked as watched on the Trakt website.

I have to clear the cache in the tools section  for the Next Up to refresh.

I am using the titan bingie skin.

**Comment by lukehansford** [comment] 2019-03-01 14:54
The same is happening with Aura skin.

A tick is placed on the episode and it is not refreshing. Even restarting Kodi and the widgets are reloaded and it does not refresh.

Going to Seren in Estuary still does not refresh Next Up

**Comment by lukehansford** [comment] 2019-03-01 14:57
https://ibb.co/2thzJd2

**Comment by nixgates** [comment] 2019-03-01 14:58
Got a few questions that I need to cover here:

Is it the latest episode released?
How long is the episode?
How long after the episode did you refresh the list?

**Comment by lukehansford** [comment] 2019-03-01 15:08
Yes the latest episodes are from 2017 but it happens even on one's released last week.

Episode is 43 minutes. 

I refreshed the list even half hour later.

I have tested if you mark as watched in Trakt on the website the Next Up is still not updating. 

I have also marked as watched manually with the Trakt manager and it does not update. 

The only way to get the Next Up to update is to clear the cache under tools.

**Comment by lukehansford** [comment] 2019-03-01 15:12
I just clicked on mark as watched the latest episode of Roswell New Mexico released a few days ago in the Trakt manager menu in Seren Next Up and it is marked as watched on the Trakt website.

When I exit Next Up list and re-enter the episode has a tick next to it same as before.

**Comment by nixgates** [comment] 2019-03-01 15:13
Just one last question before I start looking into it, is the episode being marked as watched correctly on Trakt?

**Comment by lukehansford** [comment] 2019-03-01 15:21
Yes the episodes are both marked as watched in Trakt history section on the Trakt website.

Here you can see from these screenshots.

Something has stopped the Next up from refreshing.

You can see that Roswell New Mexico and the blacklist have watched ticks next to them.

https://ibb.co/z8W6Npv

Here you can see both episodes are marked as watched under the history page on the Trakt website. 

https://ibb.co/Q8NPRGG

When I clear cache under tools in Seren the list has then updated.

You can see the Roswell New mexico episode has dissapeared because it was this week's airing episode and the black list is showing episode 19 as it should.

**Comment by nixgates** [comment] 2019-03-01 15:24
Ok easy enough, that puts it down to a caching issue of Trakts next up data.

I'll put a temporary fix in the next update. This may cause minor slow downs in the menu for the interim until the full Trakt information syncing is completed.

Please let me know if this issue is still present after 0.1.36

**Comment by lukehansford** [comment] 2019-03-01 15:35
Did it get broken in 0.1.35 or has Trakt changed something? 

I'm surprised no one else has reported it.

I have just wiped Kodi 18.1 stable and installed Seren and only Seren with default settings on default estuary skin.

I do not have the Kodi Trakt separate addon installed at all if that helps.

I set two episodes mark as watched with the Trakt manager of the context menu in the Next up section. 

They both show then as watched on the Trakt website but the add-on has tick marks next to them when I exit and re-enter the Next Up list.

This proves it is not related to using a skin.

**Comment by nixgates** [comment] 2019-03-01 15:39
Looks like something is going wrong with the caching of the data. This data should be refreshed every half an hour if requested but apparently doesn't seem to happening.

Nothing has changed in Seren to expect this type of behaviour.

That's about all I can say at the moment, I'll have to look into it and figure out where the issue stems from and then identify where the issue came from.

**Comment by lukehansford** [comment] 2019-03-01 15:50
Is it happening on a fresh install on Kodi 17.6 for you also?

It used to refresh the next up list every time you entered the section which is what we need especially if you use a skin with widgets. 

Only thing that is working now is clearing the cache Evey time.

**Comment by drinfernoo** [comment] 2019-03-01 17:42
@lukehansford You just spammed about 25 of the exact same question regarding this on the subreddit, even saying that you know it's an issue, and that the developer (nixgates) is aware and looking into a fix. I'll be removing them as soon as Reddit is back up.

**Comment by icpryde** [comment] 2019-03-04 05:27
Also note it doesn’t update immediately, for example I watch an episode and finish it next up will still show the episode I watched even if it’s 3 episodes I finished. After a few minute though let’s say 10 min or 30 min it will update to the appropriate episode that I haven’t watched yet. So for me looks like it’s working as intended ?

**Comment by lukehansford** [comment] 2019-03-04 15:30
This seems to have to have fixed itself now. 

Must have been something to do with Trakt and not the add-on. 

Hope the Dev will see this and not need to add the the temporary fix that would result in the Next UP list slower to load.

**Comment by lukehansford** [comment] 2019-03-04 19:57
The caching bug where it places watched ticks next to the episode seems to have fixed itself.

When you press the Kodi stop button when the credits show for a watched TV show episode in Next Up and then exit the list. When you re-enter Next Up the list is updating immediately.

Strange.

**Comment by lukehansford** [comment] 2019-03-04 19:59
The caching bug where it places watched ticks next to the episode seems to have fixed itself.

When you press the Kodi stop button when the credits show for a watched TV show episode in Next Up and then exit the list. When you re-enter Next Up the list is updating immediately.

Strange.

**Comment by nixgates** [comment] 2019-03-05 00:27
Closing as the issue appears to be related with Trakt Server issues

**Closed by nixgates** 2019-03-05 00:27 UTC

**Comment by lukehansford** [comment] 2019-03-05 16:33
The caching bug has started again and is not fixed. I spoke too soon my apologies.

We need the fix in 0.1.36 as mentioned.

This is from a total Fresh install of Kodi 18.1 final with the only setting to in Seren changes being autoplay set to list. Authorised Trakt and real debrid and install providers. 

This is what is happening. 

https://ibb.co/YRVTWLQ

You still get these two ticks next to each episode and they are both marked as watched on the Trakt website.

It must be how Seren is refreshing the list. Maybe Trakt changed the API.

The issue is not happening in other add-ons such as Gaia and Realizer, however they do use the Trakt - Progress section not sure if that makes a difference. 

If you see on Trakt's Twitter page they have made some changes to the next up section on the Trakt website.

When the list is refreshed either manually or by a skin such as titan or AuraMod the episode does not dissapear or update.

Having the clear cached under tools section everytime to update the list.

Is it possible to get Next Up to changed it so it requests an update from Trakt each time the list is loaded?

**Comment by lukehansford** [comment] 2019-03-07 02:47
The Next Up section seems to be refreshing correctly now. 

Tested using Bingie skin
