### ISSUE TITLE
Seren randomly losing trakt and RD credentials

### ISSUE THREAD

**Issue by dimdam** [nixgates/plugin.video.seren#18] opened 2018-12-22 22:38 UTC
What the title says and here is the log file: 

https://pastebin.com/2FyL5yWC

**Comment by nixgates** [comment] 2019-01-10 08:16
This has been identified and I'm investigating it as closely as possible but yet to locate any reasoning for it.

I have a hunch it has to do with threading but that's just a very loose hunch with no evidence. 

I'll leave this thread open as the main github thread to track this issue. Thank you for reporting it.

**Comment by mophawka** [comment] 2019-01-11 05:59
@nixgates not sure if this is related but i do see a ton of "threading" error in directories/list that has a huge amount of shows/movies/ and have lost seren credentials right after. with lists close to 500 or more items.

**Comment by nixgates** [comment] 2019-01-11 06:19
Can you get me a copy of that log? That would be helpful.

**Comment by mophawka** [comment] 2019-01-11 22:57
of course!  https://pastebin.com/R0PqPwv2

as i stated no clue if this is related but here an example of trying to access to the TV Collections directory with no success. in the end kodi had to alt f4 to be closed.

**Comment by nixgates** [comment] 2019-01-13 05:04
I've managed to re-create the settings loss issue and as I suspected, it does seem to be due to to many threads changing settings at once.

So from my tests, there are three things I can confirm:

- It is less likely to occur on RC versions of 18 (18 was able to handle massive amounts of threads without failure)
- It's reproducible by generating multiple instances of the python interpreter and then spawning large amounts of threads that alter Seren's settings
- Multi widget skins like Aura are more likely to be affected by this than others

**Comment by mophawka** [comment] 2019-01-13 06:08
@nixgates > thanks for looking into this. As you can see the log is from kodi 17.6 using the Xonfluence skin but with no widgets used. those errors were all generated when attempting to get open the TV Collections directory with over 500 items. nothing else was attempted due to Kodi crashing at the end. Thanks!

**Comment by mophawka** [comment] 2019-01-14 04:00
@nixgates took previous post into consideration and updated to Leia RC1 did not see much of threading errors and did not lose seren credentials but still cant open the collections directory. just hung with spinning wheel for over 30 minute and had to alt 4 to close kodi. let me know if this is an entirely different issue now and i will open a create a new issue. again this is Xonfluence skin with no widgets. opened seren and went right to collections directory.

Log: https://pastebin.com/1k8i3LnY

**Comment by mophawka** [comment] 2019-01-18 07:20
@nixgates the issue was reported in previous post with log was after updating to v 0.1.25. Its in the log line "88: 17:48:37.622 T:8592  NOTICE: ADDON: plugin.video.seren v0.1.25"

Thanks

**Comment by nixgates** [comment] 2019-01-31 22:36
@mophawka

Could you please raise a seperate issue for this.
This is generally due to users who have rather large collections or trakt history.

I have a work around for this that I want to introduce but would prefer to monitor it in a seperate issue.

**Comment by nixgates** [comment] 2019-02-08 13:17
I have re-open this issue as it the patch applied does not appear to cover all use cases.

The issue still remains that Kodi's setting calls are not thread safe.

A permanent fix will require a seperate add-on to handle settings for Seren in a thread safe manner.

**Comment by nixgates** [comment] 2019-12-17 01:30
This issue appears to be long gone on more stable releases of Kodi. 

Closing it off :)

**Closed by nixgates** 2019-12-17 01:30 UTC
Labels: Kodi Based Issue, bug
