### ISSUE TITLE
[REQUEST] Filter for Atmos/Dolby Vision to exclude from results (similar to quality filter)

### ISSUE THREAD

**Issue by henryjfry** [nixgates/plugin.video.seren#591] opened 2021-04-03 12:34 UTC
I think it would be useful if there was a setting option to automatically exclude Atmos/Dolby Vision results where these files cannot be played on your device?

I've attempted to implement this myself but wasnt able to get it to reliably work to exclude Dolby Vision files from the search/cache and not mess up the sources list (wrong qualitys being returned, presumably because im excluding items rather than deleting them from all the lists they appear on).

However I suspect this would be a relatively simple thing to implement, just include atmos as another quality to determine inclusion/exclusion?

Cheers

**Comment by drinfernoo** [comment] 2021-04-03 15:07
Duplicate of #533.

**Closed by drinfernoo** 2021-04-03 15:07 UTC
Labels: enhancement
