### ISSUE TITLE
[BUG] Seren v2.0.9 Bugs that I found till now

### ISSUE THREAD

**Issue by ShibajiCh** [nixgates/plugin.video.seren#328] opened 2021-01-04 16:41 UTC
Hi,

Below are the bugs that I noticed till now in the Seren v2.0.9 add-on.

1) Trakt tracking is not working all the time for mainly TV Shows. I've to go to Trakt website and add an episode as watched manually and then re-sync in Seren.
2) If I play a TV show completely without pause, forward or rewind, the Trakt tracking is not working sometimes or only half of the episode is being tracked as played.
3) Receiving "Unknown error connecting to Trakt" message after completely playing a TV show episode.
4) "Playing Next" dialog box is not appearing for any of the TV Shows before 30 seconds when the show is about to end.
5) Even after sorting the "Next Up" Episodes list as "Recently Watched" the list is not sorting accordingly sometimes.
6) In the scraping page, the media details for the video, such as file type, audio and video format, audio channels, etc. details are missing.
7) The posters for all the TV shows are not of the recent seasons like it used to be earlier. They are from past seasons.
8) While trying to open the "New TV Shows" list it is throwing "Seren Error" and the list is not opening.

I'm currently using Kodi v18.9 in both Android and Windows devices and found the same issues as mentioned above replicating everywhere.

Please look into these issues and kindly do the needful. Thank you!

**Comment by jweinreich** [comment] 2021-01-04 17:30
Shield TV user here.
1.2.3 Can't help since I authorized trakt but disabled scrobling and let the official trakt addon do the work.
4. Did you enable Episode Play Style: "Auto Play" in settings? and just in case did you enable pre-emtive scraping? "Playing Next" dialog works ok here.
5. Don't understand, sorry.
6. Where are you scraping from? Usually that information is seen on the file description for each source.
7. What prefered artwork source do you use in Settings: Artwork? If you use fanart.tv you might need to set up an API key. I use TMDb as prefered and haven't had any issues.
8. This error has been confirmed.

Cheers,

**Comment by peno64** [comment] 2021-01-04 19:41
I can confirm the problems about trakt a bit. Yesterday I watched 2 episodes of a series and the first one was checked in trakt, but the next one that auto searched after the first and played until the end wasn't.

**Comment by Dealz-416LS** [comment] 2021-01-05 06:28
@jweinreich 

It’s strange, If I turn off scrobbling in Seren there is zero communication (check in) with Trakt during playback, the show/movie isn’t even marked as watched.

The only way for me to make it work (Resumes, Marked as watched & Rating) is to have Scrobbling turned on for both Seren and the Trakt add-on but iirc @nixgates said in a Reddit post having them both on isn’t  recommended but nothing works with either of them off.

**Comment by jweinreich** [comment] 2021-01-05 10:28
Sorry I wasn't accurate, I had disabled seren trakt scrobling and was
manually marking content as watched using the trakt addon.
I don't expect the trakt addon to scroble web content that is not in your
library, but I may be wrong here, with lack of documentation and poorly
explained menus we just have to trial and error.

For now I will disable trakt addon completely and watch how seren behaves.

This trakt clarification merits a forum post I think.

Cheers

**Comment by Dealz-416LS** [comment] 2021-01-05 12:25
@jweinreich  no worries, thanks for clarification. Before 2.0 the Trakt add-on handled everything from Seren just fine Resumes (Check ins), Auto marking as watched etc now from my experience it doesn’t do anything unless Seren scrobbling is checked which is odd as it did it all fine before Seren got that option.

**Comment by nixgates** [comment] 2021-01-05 21:56
1) Looks like there was a lot of connection issues to trakt yesterday. There's a few workarounds going into Seren to make sure they don't break other parts but I can't fix Trakt API not responding properly. There was a lot of time outs from some users yesterday and 502 (server errors) I'm hoping these will pass.

Please see bug #281

2) Same issue as 1

3) Same issue as 1

4) Funnily enough, same as 1

5) Can you expand on this, what about the sort is wrong?

6) The details aren't available on the scrape dialog, they are available on the source select dialog and have always been there. They are on the bottom right hand side of each source card.

7) I'll look into it, but show artwork is based on what the meta provider gives us, there's no fetching for newer artwork and never was.

8) Please see bug #273

**Comment by nixgates** [comment] 2021-01-05 21:58
I'm closing this off, @ShibajiCh as most of it is just duplicates of the above mentioned references.

If you want, please feel free to raise separate issues for 5) and 6)

**Closed** 2021-01-05 21:58 UTC
Labels: bug, duplicate
