### ISSUE TITLE
New tv shows menu not working

### ISSUE THREAD

**Issue by kodi-lover** [nixgates/plugin.video.seren#273] opened 2021-01-02 13:46 UTC
In the discover tv shows menu, I've tried almost every menu and they all load a list but only new tv shows keeps throwing a seren error check log.

Please see below log:

https://paste.ubuntu.com/p/8Pcy8sk3HY/

**Comment by xyzfre** [comment] 2021-01-03 00:06
Same here every menu in Discover TV shows￼ loads except for New TV shows I also get a error￼

**Comment by nixgates** [comment] 2021-01-03 03:00
Something looks wrong with your sync database, apologies but you'll have to try re-build it. This may have been caused by the weird issues with the initial 1.6->2.0 migration that didn't go well on release.

If the rebuild fails, you may need to manually delete the following files from here "Kodi\userdata\addon_data\plugin.video.seren":
traktSync.db
traktSync.db.md5

**Comment by xyzfre** [comment] 2021-01-03 03:54
I manually deleted the files you requested but still get the same error when trying to open New TV shows

**Comment by nixgates** [comment] 2021-01-03 04:37
@xyzfre give a minute here, I can what's causing it. There's a bit of bad data in the SQL query. I'll have to find out how that's getting there

**Comment by nixgates** [comment] 2021-01-03 04:45
I'm able to re-create the issue, going over it now

**Comment by arcsur** [comment] 2021-01-03 05:49
Issue relates to the JSON coming back from Trakt API.

This is the offending entry: 

`{'trakt_id': 4685207, 'episode': {'trakt_id': 4685207, 'trakt_object': {'info': {'sortseason': 1, 'aired': '2020-12-31T21:00:00.000Z', 'rating.trakt': {'rating': 0, 'votes': 0}, 'tmdb_id': 2602614, 'rating': 0.0, 'season': 1, 'mediatype': 'episode', 'trakt_id': 4685207, 'plotoutline': 'Olympia (‘Oly’) Chalmers-Davis, an ambitious and organised Year 11 student, is blindsided when the long-delayed consequences of one impulsive decision suddenly blow up on her.', 'duration': 1800, 'episode': 1, 'plot': 'Olympia (‘Oly’) Chalmers-Davis, an ambitious and organised Year 11 student, is blindsided when the long-delayed consequences of one impulsive decision suddenly blow up on her.', 'votes': 0, 'dateadded': '2021-01-03T08:05:13.000Z', 'sortepisode': 1, 'title': 'Sorpresa!', 'available_translations': ['en'], 'premiered': '2020-12-31T21:00:00.000Z', 'originaltitle': 'Sorpresa!', 'sorttitle': 'Sorpresa!'}}, 'tmdb_id': 2602614}, 'show': {'status': 'returning series', 'rating': 7.0, 'votes': 1, 'network': 'Stan', 'language': 'en', 'title': 'Bump', 'overview': 'From the team behind Love My Way and The Secret Life of Us comes the Stan Original series Bump. The series centres around Oly, an ambitious and high-achieving teenage girl who has a surprise baby; and the complications that ensue for two families.', 'available_translations': ['en'], 'year': 2020, 'ids': {'tmdb': 115639, 'tvdb': 0, 'trakt': 171569, 'imdb': None, 'tvrage': None, 'slug': 'bump-2021-171569'}, 'aired_episodes': 10, 'updated_at': '2021-01-01T22:35:25.000Z', 'country': 'au', 'comment_count': 0, 'airs': {'timezone': 'Australia/Lord_Howe', 'day': None, 'time': None}, 'first_aired': '2020-12-31T13:00:00.000Z', 'certification': None, 'runtime': 30, 'homepage': 'https://www.stan.com.au/watch/bump/', 'trailer': None, 'genres': ['drama']}, 'first_aired': '2020-12-31T13:00:00.000Z', 'type': 'mixedepisode', 'trakt_show_id': 171569}`


The 'show' value does not seem to have the same fields as others and in particular is missing the 'trakt_id' key.

A quick workaround is to add the following at line 294 of tvShowMenus.py in function shows_new() inserting before last line of function:

`trakt_list = [i for i in trakt_list if i.get("trakt_id")]`

**Comment by arcsur** [comment] 2021-01-03 05:49
hidden_items = self.hidden_database.get_hidden_items("recommendations", "shows")
        date_string = datetime.datetime.today() - datetime.timedelta(days=29)
        trakt_list = self.trakt.get_json(
            "calendars/all/shows/new/{}/30".format(date_string.strftime("%d-%m-%Y")),
            languages=self.language_code,
            extended="full",
        )
        trakt_list = [
            i.get("show") for i in trakt_list if i["trakt_show_id"] and i["trakt_show_id"] not in hidden_items
        ]
        **trakt_list = [i for i in trakt_list if i.get("trakt_id")]**
        self.list_builder.show_list_builder(trakt_list[:40])

**Comment by nixgates** [comment] 2021-01-03 06:04
Lol @arcsur I've only just seen this but also put in the exact same dirty workaround as a temporary measure.

**Comment by nixgates** [comment] 2021-01-03 06:05
Update 2.0.8 should hit the repo in a second and should provide a workaround for this temporarily

**Comment by arcsur** [comment] 2021-01-03 06:08
:)

This issue may pop up elsewhere if the trakt_id is missing when building lists, perhaps another wrapper guard function is needed longer term.  It is a bit of a pain and no idea why Trakt is returning different data for this one item.  However, so far this is the only bug in an otherwise excellent update I encountered.

**Comment by Daviddew89** [comment] 2021-01-03 06:24
Hi Nix

The new update unfortunetly did not resolve my issues with accessing "Most Popular" under "Discover TV Shows".

I have rebuild the trakt database as well with no luck.

See log:
https://paste.ubuntu.com/p/vFTdGp7bkP/

**Comment by nixgates** [comment] 2021-01-03 07:10
Ok one step further, I'm going to investigate this deeper to hopefully get a real fix for this instead of another workaround. I'm sorry but I'll have to ask you to wait just a little longer while I deep dive.

**Comment by Daviddew89** [comment] 2021-01-03 07:17
Take your time mate. Thanks again for putting so much of your time to solve this

**Comment by xyzfre** [comment] 2021-01-03 14:42
Thank you for the fix (2.0.8) ,on my end on Discover  TV shows all the sections work now except for recently updated no error pops up  just shows up blank For both recently updated for movies and TV shows,, once again thank you for this amazing update and all your hard work my friend

**Comment by DaisyF8** [comment] 2021-01-03 23:20
On 2.0.8 now. Rebuild didn't solve my problem.

Full uninstall with delete settings did. Reinstalled and then the Trakt Sync took a lot longer.

Nuclear option works 😀

**Comment by xyzfre** [comment] 2021-01-04 18:21
After Updating to 2.0.9 when going on New TV shows getting the same error as before now

**Comment by nixgates** [comment] 2021-01-06 07:05
@kodi-lover this issue should now be resolved in 2.0.1, could you please confirm?

**Comment by djdirty60** [comment] 2021-01-06 07:31
![16099181288967735515834848837594](https://user-images.githubusercontent.com/13561831/103741397-45b6f000-4ff9-11eb-962c-2df7ef35f64e.jpg)

unfortunately I only see 2 new series in the list.  assume that there should be with it and I only see the Dutch, not the English series

**Comment by nixgates** [comment] 2021-01-06 08:39
@djdirty60 if you haven't, maybe try clearing your cache and retrying? May not make a difference but best to try.

If not, could you maybe drop me a log?

**Comment by djdirty60** [comment] 2021-01-06 08:54
> @djdirty60 if you haven't, maybe try clearing your cache and retrying? May not make a difference but best to try.
> 
> If not, could you maybe drop me a log?

where can I find that log?

**Comment by nixgates** [comment] 2021-01-06 09:43
@djdirty60 hmm seems like we've found another issue in the dateutil addon. Will need to try and find a workaround.

**Comment by kodi-lover** [comment] 2021-01-06 17:11
> @kodi-lover this issue should now be resolved in 2.0.1, could you please confirm?

Yes working now, thanks Nix

**Comment by oNeXuSo** [comment] 2021-01-06 17:32
@nixgates  Just updated to 2.0.10 and this has resolved the issue with pulling new TV shows for me too. Just another reason why Seren is my no.1 addon and has been for years. I appreciate all your hard work and dedication to this project and if I could buy you a beer I certainly would!  Thanks Nix

**Comment by xyzfre** [comment] 2021-01-06 17:52
I can also confirm on my end New TV Shows are working again thank you for all your hard work Seren is AMAZING ,I notice with this last update A speed in increase￼ as well Seren seems a lot faster when it comes to opening menus etc..￼

**Comment by nixgates** [comment] 2021-01-06 21:10
Alrighty! Closing it off :)

**Closed by nixgates** 2021-01-06 21:10 UTC
Labels: awaiting completion confirmation, bug
