### ISSUE TITLE
Next-Up throwing back an error. 

### ISSUE THREAD

**Issue by bigpoppapaul** [nixgates/plugin.video.seren#768] opened 2022-05-12 05:57 UTC
I've been having this problem intermittently for the past couple weeks. It fixes itself, but then it comes back. Next-Up gets an error message, ALL the other Trakt folders work, only Next Up gets an error message. The Next Up in TMDB Helper and Venom work fine. 
I have tried clearing cache, wiping addon data, putting in my own Trakt API. None of it works. Then the issue goes away and is back again a few days later. 
Interestingly, I have an old 17.6 Kodi with an old Seren (I believe 1.6.19) that I tried updating with my own Trakt API (since the original APIs were killed off), and the issue doesn't exist there, just tested it. 

There was [another post](https://github.com/nixgates/plugin.video.seren/issues/765) about this issue last week, but when it went away, they closed it. 

Here is the debug log: https://pastebin.com/MSutAxUW

This is running on Kodi 19.4 on windows with the latest Seren.

**Comment by drinfernoo** [comment] 2022-05-12 18:11
So this isn't actually an issue with Trakt... it is an issue with OMDB.

```python
2022-05-12 01:53:21.234 T:9668    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'xml.parsers.expat.ExpatError'>
                                                   Error Contents: not well-formed (invalid token): line 1, column 123
                                                   Traceback (most recent call last):
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\router.py", line 449, in dispatch
                                                       tvshowMenus.Menus().my_next_up()
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\gui\tvshowMenus.py", line 320, in my_next_up
                                                       self.list_builder.mixed_episode_builder(episodes, no_paging=True)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\list_builder.py", line 81, in mixed_episode_builder
                                                       shows.TraktSyncDatabase().get_mixed_episode_list(trakt_list, **params),
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\database\trakt_sync\shows.py", line 342, in get_mixed_episode_list
                                                       self._try_update_mixed_episodes(trakt_items)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\database\trakt_sync\shows.py", line 762, in _try_update_mixed_episodes
                                                       self._update_episodes(episodes_to_update)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\guard_decorators.py", line 38, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\database\trakt_sync\shows.py", line 649, in _update_episodes
                                                       return self._update_objects(db_list_to_update, "episodes")
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\guard_decorators.py", line 19, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\database\trakt_sync\shows.py", line 447, in _update_objects
                                                       updated_items = threadpool.wait_completion()
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\common\thread_pool.py", line 187, in wait_completion
                                                       self._try_raise()
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\common\thread_pool.py", line 197, in _try_raise
                                                       raise self.exception  # pylint: disable-msg=E0702
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\common\thread_pool.py", line 59, in run
                                                       result_callback(func(*args, **kwargs))
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\metadataHandler.py", line 588, in update
                                                       self._add_omdb(db_object)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules\metadataHandler.py", line 599, in _add_omdb
                                                       omdb_object = self.omdb_api.get_json_cached(i=db_object.get("imdb_id"))
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\database\cache\__init__.py", line 386, in _decorated
                                                       fresh_result = func(*args, **kwargs)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\indexers\omdb.py", line 320, in get_json_cached
                                                       return self.get_json(**params)
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\indexers\omdb.py", line 78, in wrapper
                                                       return {"omdb_object": func(*args, **kwarg)}
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\indexers\omdb.py", line 299, in get_json
                                                       xml_to_dict.parse(response.text).get("root", {}).get("movie")
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\third_party\xml_to_dict.py", line 374, in parse
                                                       parser.Parse(xml_input, True)
                                                   xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 123
                                                   -->End of Python script error report<--
```

This is specifically due to OMDB sending back invalid XML data, which we've been noticing recently from OMDB. It seems they're having some type of intermittent service issues. Unfortunately, there's not much we can do about this.

However, this is basically a duplicate of #730 (in that it deals with invalid data sent back from OMDB), and that one was already addressed in our development builds. We're hoping to get a release out relatively soon that should include the fix, but I'd keep an eye on that issue, as I'll answer there when it's been merged.

**Closed by drinfernoo** 2022-05-12 18:11 UTC
Labels: bug

**Comment by bigpoppapaul** [comment] 2022-05-12 18:39
Ok Doc, thank you for the response and explanation. I'll keep an eye on #730. 

Appreciate it.
