### ISSUE TITLE
[BUG] reuselanguageinvoker causes Kodi crash

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#381] opened 2021-01-08 06:03 UTC
**Describe the bug**
Kodi crashes sometimes when trying to load widgets.  It's inconsistent when it crashes or doesn't crash, but I was able to grab a log when it crashed.  Hope it helps.

**To Reproduce**
1. Crashes after starting up kodi and widgets try to load

**Expected behavior**
Kodi should not crash.

Log:  
[kodi1.log](https://github.com/nixgates/plugin.video.seren/files/5785485/kodi1.log)

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.10
 - Skin: Aura Official

**Comment by nixgates** [comment] 2021-01-08 08:43
This is unfortunately not a Seren issue and is in fact a Kodi issue. It's been brought to their attention a few times but they have still yet to do anything about it. It's caused by the language invoker feature of Kodi. You can disable it in the settings of Seren. Just press it once, there is currently an issue in Seren where after it's pressed the value of the status doesn't change in Seren, minor issue. Will be fixed next update.

**Comment by LoganWolverineX** [comment] 2021-01-08 16:33
@nixgates thanks. I’ve just disabled it. Will update you if I encounter any other crashes.

**Comment by nixgates** [comment] 2021-01-22 02:25
@LoganWolverineX I'm going to close this off as it's not something I can fix on my end. Hopefully we will see some progression from the Kodi team about this in the future :)

**Closed by nixgates** 2021-01-22 02:25 UTC
Labels: Kodi Based Issue, wontfix

**Comment by LoganWolverineX** [comment] 2021-01-22 02:26
@nixgates thats understandable. At least I’m able to have it disabled for now to avoid any foreseen crashes. Yea hopefully kodi will get it fixed but doubt it will be fixed in v18 :(

**Comment by nixgates** [comment] 2021-01-22 07:14
> @nixgates thats understandable. At least I’m able to have it disabled for now to avoid any foreseen crashes. Yea hopefully kodi will get it fixed but doubt it will be fixed in v18 :(


Yea unfortunately there will be no more updates for v18 so it is how it is unfortunately.
