### ISSUE TITLE
Next Play TV episode in series

### ISSUE THREAD

**Issue by jokerchyld** [nixgates/plugin.video.seren#320] opened 2021-01-04 03:26 UTC
Might be a bug

In Seren 1.0 when an episode of a series ended I would get a pop up asking to play next. If I said yes the next episode would play without searching.

In 2.0 at the end of an episode it doesnt present that pop up. If the episode ends it plays the next episode but after a search.

How do I get it to operate like 1.0

**Comment by nixgates** [comment] 2021-01-04 03:32
Sounds like the background playback watcher is dying, can you please turn on debug logging get a me a debug log of you watching a episode so I can identify the root cause 👍

**Comment by nixgates** [comment] 2021-01-04 03:40
This actually looks to be a duplicate of the issue #300

Would you mind please uploading your log there

**Closed by nixgates** 2021-01-04 03:40 UTC
Labels: bug, duplicate
