### ISSUE TITLE
[BUG] "Rebuilding Trakt Sync Database, please be patient" Issue

### ISSUE THREAD

**Issue by rwarnmsn** [nixgates/plugin.video.seren#664] opened 2021-08-05 23:17 UTC
I continue to receive the "Rebuilding Trakt Sync Database, please be patient" message. On Tuesday, I followed drinfernoo's instructions in the reddit post here:   https://www.reddit.com/r/Addons4Kodi/comments/o6273i/serenrebuilding_trakt_sync_database/. After I continued to receive the message I decided to further delete Kodi and then do a clean install of Matrix 19.1 and Seren 2.1.3. Today, I proceeded to update to Seren 2.1.4 and still get the message.

**Log**

https://paste.kodi.tv/idebedifax

**To Reproduce**

No offense but it just happens. I'm not sure that the process of creating the database ever completes successfully.

**Expected behavior**

Not to continuously receive the "Rebuilding Trakt Sync Database, please be patient" message.

**Environment**

 - Operating System: Fire OS 6.2.8.1 (NS6281/3385)
 - Kodi Version: 19.1
 - Seren Version: 2.1.4

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by drinfernoo** [comment] 2021-08-06 04:03
We'll need a full debug log in order to go much further. This log stops before the Trakt sync even begins, and isn't a debug log.

**Comment by kaufman2000** [comment] 2021-08-06 13:54
I'm having the same issue with the latest update

**Comment by rwarnmsn** [comment] 2021-08-06 15:18
Drinfernoo, what do I need to do to get the log you need? Should I delete and reinstall Seren to have it recreate the database after I reauthorize Trakt? 

Ron

**Comment by drinfernoo** [comment] 2021-08-06 16:08
https://kodi.wiki/view/Log_file/Easy

I would not uninstall Seren, but just turn on debug logging, reauthorize Trakt in order to trigger a rebuild, and then upload the log.

**Comment by kaufman2000** [comment] 2021-08-06 17:22
My logfile

https://paste.kodi.tv/duwiragima

**Comment by rwarnmsn** [comment] 2021-08-06 23:06
My new log was too large to post. I'll try again later.

**Comment by Liquidrag** [comment] 2021-08-07 17:13
@drinfernoo do you want a regular log or a debugging log? I am also on a rebuilding db loop. For me, though I think it is because it never fully completes, I even have let it go for hours.

**Comment by rwarnmsn** [comment] 2021-08-08 01:38
I keep getting log files too large to post with Kodi Logfile Uploader. (I thought by exiting Kodi and restarting my Fire TV Stick but that doesn't seem to help.) Even then, I still get files biggest than 1 MB.

As I stated in my original message though, I don't think the process of creating/building the Seren/Trakt database ever completes either. I did get the following error message just now after rebuilding the database:  "Seren: Trakt" & "There were issues when processing the synchronization with Trakt, please check the log".

**Comment by drinfernoo** [comment] 2021-08-13 15:54
The log provided by @kaufman2000 does show some error... but there's no way to know if it's the same error you're getting. I'd recommend trying to get your debug log file directly, rather than trying to use the Kodi Log Uploader, since it does have a size limit.

Unfortunately, we just haven't been able to reproduce this one based on the information provided 🤷

**Comment by rwarnmsn** [comment] 2021-08-14 03:44
I have tried getting it directly and as I stated above, the last one that was created while Seren was rebuilding the database, approximately 20 minutes, is 16.6 MB!

**Comment by drinfernoo** [comment] 2021-08-14 11:34
@rwarnmsn Is your error the same as in #668?

**Comment by MikeTosen** [comment] 2021-08-14 12:56
I managed to capture the error of the rebuild loop.
On my machine the rebuild happens every 30 minutes.
[https://paste.kodi.tv/korihoxuqi.kodi](https://paste.kodi.tv/korihoxuqi.kodi)

**Comment by rwarnmsn** [comment] 2021-08-14 20:40
> @rwarnmsn Is your error the same as in #668?

@drinfernoo, I believe it is but mine started before Seren version 2.1.4, possibly in 2.1.2.

**Comment by drinfernoo** [comment] 2021-08-15 01:30
Simply for organizational purposes, I'm going to close this one. #668 seems to be a duplicate with a much more straightforward report and log.

**Closed** 2021-08-15 01:31 UTC
Labels: bug, duplicate, unreproducible, awaiting log

**Comment by drinfernoo** [comment] 2021-10-03 14:26
This should be fixed in 2.1.5, can you check?

**Comment by 0adbylad** [comment] 2022-01-03 18:57
I to get the same error
Seren rebuilding trakt sync database please be patient
[Seren error PDF.pdf](https://github.com/nixgates/plugin.video.seren/files/7803568/Seren.error.PDF.pdf)
