### ISSUE TITLE
[BUG] shortcuts for widgets via seren 2.0

### ISSUE THREAD

**Issue by Gaddinator90** [nixgates/plugin.video.seren#305] opened 2021-01-03 13:39 UTC
Ok so this is hard for me to explain but I use auramod and have widgets and category widgets set up based around seren, before 2.0 was released if i would click a show from a homescreen widget for an example it would take me to the seasons menu, and if i press back it would take me back to the widget homescreen which is fine, post update if i click on a show from the widget homescreen it will still take me to the seasons menu, except now if i press back it will not return me to the homescreen, now if i click back it refreshes the same page, I then click back again and it takes me to the discover TV shows menu within the addon, the same thing happens if i click on something from my category bar for an example, most popular, apologies if this is hard to understand but I've tried to explain it the best I possibly could, if this could be looked at it would be massively appreciated!

**Comment by SamDW96** [comment] 2021-01-03 20:33
Duplicate of #299

**Comment by nixgates** [comment] 2021-01-03 20:59
Please refer to the above issue for further tracking. 

This should be resolved in an update within the next few hours.

**Closed** 2021-01-03 20:59 UTC
Labels: bug
