### ISSUE TITLE
[BUG] UNABLE TO AUTHORISE TRAKT

### ISSUE THREAD

**Issue by thedogzeus** [nixgates/plugin.video.seren#636] opened 2021-06-21 18:32 UTC
**Describe the bug**
Unable to Authorise Trakt

**To Reproduce**
1. Go to 'Authorise Trakt'
2. Click on 'Trakt Sync Tools'
3. Scroll down to 'Force a sync with Trakt'
4. See error 'Seren Error - check log for details'

**Expected behavior**
Have tried every which way to auth Trakt. Trakt auth code popup works and successfully authenticated message appears, but when settings checked, no Trakt account present and any sync or attempt to add account again throws the error. Have dobe fresh Seren install, from a fresh install of the repo and same behaviour. Similar issue prior to update with RD, but that now appears to be OK. Also cannot access provider packages error, throws a 'Seren Error - check log' message.

**Screenshots**
N/A

**Kodi Version (please complete the following information):**
 - Kodi Version 19.1
 - Seren Version 2.1.1

**Additional context**

**Comment by thedogzeus** [comment] 2021-06-21 18:52
![20210622_042051](https://user-images.githubusercontent.com/10335482/122812920-7b366800-d311-11eb-94e3-210557012331.jpg)

**Comment by thedogzeus** [comment] 2021-06-21 18:53
![20210622_042023](https://user-images.githubusercontent.com/10335482/122813012-96a17300-d311-11eb-9f8f-4635cb7dc6c5.jpg)

**Comment by thedogzeus** [comment] 2021-06-21 18:53
![20210622_041958](https://user-images.githubusercontent.com/10335482/122813053-a15c0800-d311-11eb-939e-fd98b1ec2825.jpg)

**Comment by thedogzeus** [comment] 2021-06-21 18:54
![Uploading 20210622_041943.jpg…]()

**Comment by thedogzeus** [comment] 2021-06-21 18:54
![20210622_041930](https://user-images.githubusercontent.com/10335482/122813123-b89af580-d311-11eb-8457-ab50e39909cc.jpg)

**Comment by thedogzeus** [comment] 2021-06-21 18:54
![20210622_041822](https://user-images.githubusercontent.com/10335482/122813148-c3558a80-d311-11eb-8f3f-10fc43ee9737.jpg)

**Comment by thedogzeus** [comment] 2021-06-21 18:55
![20210622_041759](https://user-images.githubusercontent.com/10335482/122813189-cea8b600-d311-11eb-9b93-a112481f7558.jpg)

**Comment by thedogzeus** [comment] 2021-06-21 18:55
![20210622_041708](https://user-images.githubusercontent.com/10335482/122813226-d9fbe180-d311-11eb-8899-6dbe1085a012.jpg)

**Comment by thedogzeus** [comment] 2021-06-21 18:55
![20210622_041705](https://user-images.githubusercontent.com/10335482/122813261-e5e7a380-d311-11eb-80cf-59de1290315d.jpg)

**Comment by thedogzeus** [comment] 2021-06-21 18:56
![20210622_041636](https://user-images.githubusercontent.com/10335482/122813288-f0a23880-d311-11eb-924b-019f9cb0584c.jpg)

**Comment by drinfernoo** [comment] 2021-06-21 21:12
Please attach an actual debug log.

**Comment by thedogzeus** [comment] 2021-06-22 15:52
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6695738/kodi.log)

**Comment by thedogzeus** [comment] 2021-06-22 15:56
Log attached above ⬆️ #

**Comment by thedogzeus** [comment] 2021-06-22 16:02
Now attached. And here it is aswell...incase dl link in thread is flakey

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by drinfernoo** [comment] 2021-06-23 14:15
Looks to me like a corrupt database file (or two)... Are you running this in a build? If so, I'd recommend trying it out in a clean install, and if you can reproduce it there as well, then attach a debug log.

**Comment by JackDinn** [comment] 2021-06-25 18:05
Iv just installed a brand new kodi 17.1, All was going fine, but seren started failing to update the watchlists from trakt a couple of days ago(ish). I de-authorised it cleaned all the cache etc, rebooted kodi but it will not allow me to authorise trakt again?

![Kodi_20210625_185557](https://user-images.githubusercontent.com/5557560/123466895-cb4e4c80-d5e7-11eb-9adb-9e0f129a8689.png)

The Oath is deauthorizing & pre-authorizing fine? Seren just will not 

kodi 17.1 (on shield)
seren 2.1.1

**Comment by JackDinn** [comment] 2021-06-25 18:29
Full log if needed https://pastebin.com/3ZLa4QEH

**Comment by drinfernoo** [comment] 2021-06-25 19:18
@thedogzeus For the original issue, it seems pretty clear that there are widespread issues with your install, most likely stemming from an unmaintained and/or faulty community build.

@JackDinn Try again later. That is a different error message, indicating that you are being rate limited due to too many API calls in a short time.

**Comment by JackDinn** [comment] 2021-06-25 19:26
> For the original issue, it seems pretty clear that there are widespread issues with your install, most likely stemming from an unmaintained and/or faulty community build.

Not sure what this means, what widespread issues? i just followed https://www.reddit.com/r/Addons4Kodi/comments/lv1w2d/recommended_addons_1st_half_2021/ for Seren a week ago.

> Try again later. That is a different error message, indicating that you are being rate limited due to too many API calls in a short time.
I shall do that, thx.

**Comment by thedogzeus** [comment] 2021-06-25 20:53
Oky dokes, update; on a clean install of Kodi 19.1 all errors re authentication are cured. However, upon restart of Kodi; Trakt, RD and Premiumize auths are all lost and all custom settings are returned to default (not saved). I will run a few more cycles later to see if its a one off or consistent and post back in due course. Nb. Props to the Dr for the time and energy invested on the project, respect is due 🤘

**Comment by Chucknorris1975** [comment] 2021-06-27 00:15
> Oky dokes, update; on a clean install of Kodi 19.1 all errors re authentication are cured. However, upon restart of Kodi; Trakt, RD and Premiumize auths are all lost and all custom settings are returned to default (not saved). I will run a few more cycles later to see if its a one off or consistent and post back in due course. Nb. Props to the Dr for the time and energy invested on the project, respect is due 🤘

Any luck?

**Comment by thedogzeus** [comment] 2021-06-27 01:15
No joy on clean vanilla Kodi install or fresh Xenon community build. Both dropped the authorizations after about 30 min. Will shelve this one for now and see how future release(s) go.

**Comment by drinfernoo** [comment] 2021-06-27 02:06
Are you allowing the database rebuild to fully complete after authorizing Trakt?

It should give notifications of it's progress along the way, and a final notification indicating that it finished successfully.

**Comment by thedogzeus** [comment] 2021-06-27 07:30
Hi Dr, yeah Trakt sync progress is displayed and successfully completes, in both environments. Auth and sync has been performed both with and without VPN and de-auth issue still presents. Co-incidently, during the short period that the authorisations do stick (RD and PM), the scrapers fail to find any links, so Im not 100% confident calls to the providers are actually being successfully completed either. I dunno. Perhaps it could be a quirk in my native Android TV environment that is packaged with my Kogan TV. I'll stay tuned for new releases and try again down the track. I've got plenty of other things to occupy my mind atm, so Kodi time is pretty limited right now anyways 👍

**Comment by drinfernoo** [comment] 2021-07-02 02:13
This should be fixed in 2.1.2.

**Closed by drinfernoo** 2021-07-02 02:13 UTC
Labels: Awaiting Log, Unreproducible, bug, question
