### ISSUE TITLE
Inspect Cloud Files on Scrape issue

### ISSUE THREAD

**Issue by icpryde** [nixgates/plugin.video.seren#118] opened 2019-05-14 16:51 UTC
Hey Nix, I noticed something with this. If I have an individual file whether its a movie or show then this feature seems to be working. Though if I have an entire season cached on my cloud then Seren doesn't seem to scrape it from the cloud.

Here is a log file:

https://paste.kodi.tv/alikimekir

**Comment by lukehansford** [comment] 2019-05-14 21:15
Seren could not find the latest release for the Greta film from rarbg latest releases bar.
Greta.2018.1080p.AMZN.WEBRip.DDP5.1.x264-NTG

I added it to my real Debrid cloud but Seren cannot scrape it. 

It shows in my files. 

Don't think this just affects season packs.

**Comment by nixgates** [comment] 2019-05-14 22:43
Yea it has a few bugs as was not really ready for release. Unfortunately there was a lot of push back about the next up not refreshing which was included in this release.

In the end I had to push through the update early to overcome that issue. The cloud file inspection is still being worked on and I'll hopefully have it ironed out by next update.

**Comment by nixgates** [comment] 2019-05-20 06:30
@lukehansford can you confirm if the issue is now resolved with version 0.2.35 :+1

**Comment by icpryde** [comment] 2019-05-20 17:38
@nixgates I just tested the feature and it seems to be working great! scraping is even faster now if you got the files on your cloud! Amazing job!

**Closed** 2019-05-22 01:32 UTC
Labels: awaiting completion confirmation, bug
