### ISSUE TITLE
Something broke the addon between 0.2.24 and  0.2.30 on AppleTV with Kodi 17.6

### ISSUE THREAD

**Issue by kartana** [nixgates/plugin.video.seren#113] opened 2019-05-10 17:55 UTC
I hate posting this without a log but I haven't figured out how to copy it from my AppleTV install. I can view the log but not copy it over.
Version 0.2.24 runs flawless but I just installed 0.2.30 (fresh Kodi install) and everything breaks. First error with Trakt authorization and then searches don't work and nothing shows up in top movies etc.. It throws a bunch of python errors.
Going back to 0.2.24 and all runs well. Can anyone tell me how I could provide more feedback?

**Comment by andrewgribben** [comment] 2019-05-10 23:22
I'm having the same problem and had to roll back too. I'll update again and pull the Kodi logs in the morning.

**Comment by kartana** [comment] 2019-05-12 07:58
Are you on AppleTV too?

**Comment by andrewgribben** [comment] 2019-05-12 08:30
Yes

**Comment by MatthieuLab** [comment] 2019-05-12 14:31
Same here!
I know have to figure how I can grab the previous version!

**Comment by MatthieuLab** [comment] 2019-05-12 14:53
Ok, I have clone the git, checkout a 0.2.23 commit, zip the rep and it's fine now.

**Comment by kartana** [comment] 2019-05-12 17:23
Was anyone able to get a log file?

**Comment by neutroh** [comment] 2019-05-12 18:32
I’m having the same issue on 0.2.30. Nothing works. Clicking literally any menu item within Seren causes “Seren error” notification toast in Kodi. Can’t view any media since it looks like Seren is totally broken in this release. Kodi Log Viewer shows them all to be python errors. I can attempt to take a picture of the logs and post some Imgur links, since there doesn’t seem to be a way to extract logs from the Apple TV.

**Comment by kartana** [comment] 2019-05-14 11:11
Ok, amateur hour but here is a screenshot of the error message I get when searching for a tv show (only happening on v0.2.30)

![IMG_0219](https://user-images.githubusercontent.com/8889810/57693552-ccab9d80-7649-11e9-9474-108335bb4046.JPEG)
![IMG_0220](https://user-images.githubusercontent.com/8889810/57693557-ce756100-7649-11e9-93a2-0483d9a3002d.JPEG)

**Comment by nixgates** [comment] 2019-05-14 23:36
That looks more like Kodi is not returning a number from the settings.

Can you open Seren's settings and in the general tab, set the item limit per page to a number?

@kartana

**Comment by kartana** [comment] 2019-05-15 06:53
Thanks for replying @nixgates. The limit is set to the default 40. I tried to change it just to make sure but I get the same problems. 

Here is the error message if I try to click on a TV Show I had set as a favorite in Kodi before updating to 0.2.30.

![1](https://user-images.githubusercontent.com/8889810/57754508-eb17a480-76ee-11e9-9e31-250ff273361a.jpg)
![2](https://user-images.githubusercontent.com/8889810/57754510-ec48d180-76ee-11e9-94eb-08c6d19d61d4.jpg)

The first error I've got when setting up a fresh Kodi with the latest Seren version (0.2.30) was when I did change the settings and tried to authorize Trakt. I can try to recreate this if you want to see what error message comes up in the log. Or maybe set it up fresh without Trakt and see if that works.

Other problems I noticed were that the movie search just shows a blank page while the tv search brings up the field where you have to type in the name of the show as you would expect. This is with search history on or off. If I set search history to on I get a blank page for both movie and tvshow when I click on search tv show / search movie.

**Comment by busherz** [comment] 2019-05-17 04:44
I also have the same issue as above.With my 4K Apple TV Search stopped working and went blank on 0.2.24 and now with 0.2.30 I just get an error.

With Apple TV 4 search still works but I get the same error!

Kodi 17.3 on both

**Comment by kartana** [comment] 2019-05-17 06:04
> I also have the same issue as above.With my 4K Apple TV Search stopped working and went blank on 0.2.24 and now with 0.2.30 I just get an error.

For version 0.2.24 just disable "search history" and it should work fine.

**Comment by kartana** [comment] 2019-05-18 09:44
So I did the following:
1. uninstalled Seren
2. made sure both the addon folder and the folder inside userdata are gone
3. installed Seren 0.2.30 fresh
This is the first error message I've got without even touching the settings:

![1](https://user-images.githubusercontent.com/8889810/57967653-ddb62080-7961-11e9-9703-f743aaa19a86.jpg)
![2](https://user-images.githubusercontent.com/8889810/57967654-df7fe400-7961-11e9-8823-64178a71ac85.jpg)
![3](https://user-images.githubusercontent.com/8889810/57967655-e0b11100-7961-11e9-87df-0a4f8520e396.jpg)

**Comment by nixgates** [comment] 2019-05-20 05:12
@kartana Can you please find the settings.xml file in the following folder:

> userdata>addon_data>plugin.video.seren

Inside this file is a line that will look similar to this:
>     <setting id="item.limit">40</setting>

Could you please reply with this line

(please make sure to only copy this line over, this file will contain sensitive data so make sure to copy only this line)

**Comment by kartana** [comment] 2019-05-20 10:52
@nixgates 

`<setting id="item.limit" value="40" />`

**Comment by kartana** [comment] 2019-05-21 07:26
It seems to try to convert an argument that it gets as a string into an integer but can't, possibly because of a comma or something.

**Comment by nixgates** [comment] 2019-05-22 01:35
@kartana yea it sounds like Kodi is doing something weird with it's settings on the apple TV device.

If you are up to testing it out with me, I'd need to send you a custom version of Seren that will provide me a bit more information in the log so I can get and idea of where the hell this is failing.

**Comment by kartana** [comment] 2019-05-22 08:23
Yes, sure. I think I might even be able to provide the full logs without having to use screenshots.

**Comment by nixgates** [comment] 2019-05-31 01:07
I'm going to try and get my hands on an Apple TV this weekend and have a look.

The Apple TV is doing a lot of weird things that I'm really going to have to look at personally.

**Comment by eblin** [comment] 2019-05-31 03:22
Hey @nixgates I debugged this on my ATV and it seems on initial launch all settings are empty, since you are caching the settings after that it just keeps failing over and over on same setting. For some reason the ATV doesn't write the initial settings.xml on addon install as I suspect happens in other devices.

https://github.com/nixgates/plugin.video.seren/blob/master/resources/lib/indexers/trakt.py#L138

Fix is rather simple, `item.limit` is blank on initial launch, however I don't see the necessity of converting to int since you are basically just passing it to the trakt api `?limit=%s` query string, should be fine without the int casting. You also have the same on `post_request`  https://github.com/nixgates/plugin.video.seren/blob/master/resources/lib/indexers/trakt.py#L174

That takes care of first error, after that the check for `item.limit` in `showsNetworkShows` fails again for the same reason (blank value), this one does need to be casted to int since you are comparing it to the len of `task_list`, anyways I'm sure you know how to fix it just a matter of setting a default value in case is blank https://github.com/nixgates/plugin.video.seren/blob/master/resources/lib/gui/tvshowMenus.py#L277

```if len(trakt_list) == int(tools.getSetting('item.limit') or 40):```

I guess you could make this more pythonic if you modify getSetting to accept a `default` kwarg to mimic python's `dict.get`

I made some other changes as well, if you don't mind I can send you a PR, let me know.

and last but not least, thanks for all the work on seren 👍

**Comment by nixgates** [comment] 2019-05-31 06:29
Ah! That would have taken me an enternity to identify without an ATV.

I'll just make a change for that device so the settings don't get cached in the next update. 

But I'd love to see a PR 🙏

**Comment by kartana** [comment] 2019-05-31 06:45
Thanks for taking your time to figure this out! @eblin

**Comment by busherz** [comment] 2019-05-31 06:48
Nice work thanks!

**Comment by eblin** [comment] 2019-05-31 14:00
No problem, thanks!

> I'll just make a change for that device so the settings don't get cached in the next update.

The caching of settings works fine after initial launch, I don't think that's the issue.

I think the issue with caching settings is that you are not clearing cached settings on `setSetting`, because even though setting gets updated fine thru `xbmcaddon.Addon().setSetting` call when you are retrieving them you're checking the cache dict first and then returning (which is great) but you will never get new settings since the cache is stale at that point.

A quick check if setting is cached delete then set new value is what I did...

```py
def setSetting(id, value):
    if id in SETTINGS_CACHE:
        del SETTINGS_CACHE[id]
    if not console_mode:
        return xbmcaddon.Addon().setSetting(id, value)
# ... rest ...
```

Haven't checked thoroughly but I believe this also causes the bug I'm seeing where the trakt sync activities dialog shows up even though there is no trakt account saved, I'll check later

Anyways, I'll send you a PR so you can review the changes

**Comment by diemenz** [comment] 2019-06-01 16:18
I am looking forward to this PR being submitted as I also have an Apple TV 4K and haven’t been able to fix this.

**Comment by nixgates** [comment] 2019-06-01 18:31
The issue is Kodi doesn't update the setting outside the python interpreter.

The only reason the settings cache is there is to minimise the log output about the settings being in the old format that the Kodi team apparently refuse to remove so this can be omitted for Apple devices

**Comment by nixgates** [comment] 2019-06-01 18:32
In short there should be no disadvantage to disabling the cache

**Comment by diemenz** [comment] 2019-06-10 22:06
I sign in everyday checking to see if this fix was merged lol.

**Comment by eblin** [comment] 2019-06-10 22:48
> I sign in everyday checking to see if this fix was merged lol.

I believe @nixgates already implemented it in the code not sure if he has released it though see: #128

**Comment by Royv1981** [comment] 2019-06-12 08:27
I test it, but it don't work by my on this moment. Is the fix already released?

**Comment by diemenz** [comment] 2019-06-16 02:46
There hasn’t been a new version so I’m assuming it’s not out yet

**Comment by diemenz** [comment] 2019-06-23 07:21
I have tried making these edits myself to get it working but have been unsuccessful and still get the error. I rolled back to the last working version in the meantime.

**Comment by kartana** [comment] 2019-06-23 07:37
Did they come for @nixgates too? He hasn't commented since June 7. Hope he is just busy with other stuff.

**Comment by busherz** [comment] 2019-07-06 16:43
any update?

**Comment by kartana** [comment] 2019-07-06 16:47
@nixgates hasn't posted anything for 1 month now. I hope this project isn't dead.

**Comment by drinfernoo** [comment] 2019-07-06 17:07
@kartana Seren is far from dead... things just take time 👌

**Comment by nixgates** [comment] 2019-07-15 00:14
@kartana @busherz 

Apologies, I wanted to push this earlier but I kept running into things and really wanted to push out a polished update this time.

Please note, the issue has been resolved with the latest update. If could check and confirm that would be very appreciated :+1:

**Comment by diemenz** [comment] 2019-07-15 02:03
So far so good nix. Will keep checking it out over the next few days

**Comment by busherz** [comment] 2019-07-15 15:18
Thanks @nixgates

Everything working good!

**Comment by nixgates** [comment] 2019-07-16 06:17
Alright, I'll close this bad boy off. 

Let me know if it comes back

**Closed by nixgates** 2019-07-16 06:17 UTC
Labels: awaiting update, bug
