### ISSUE TITLE
Increase loading speed up of Next Up section

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#80] opened 2019-03-25 23:39 UTC
Is it possible for a future update to speed up the loading of the next up section?

Or add another "trakt progress" section like other addons such as Yoda, Gaia and Realizer.

The Trakt progress sections on these add-ons load significantly faster.

Mostly noticeable if using skin widgets in popular skins such as titan and aura.

**Comment by nixgates** [comment] 2019-03-31 23:31
Please note, this is a duplicate issue
Duplicate of #39

Next update should help to resolve this issue as the caching of menu items has changed drastically.

**Closed by nixgates** 2019-03-31 23:31 UTC
