### ISSUE TITLE
Seren episodes being marked as watched multiple times

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [nixgates/plugin.video.seren#48] opened 2019-02-14 21:05 UTC
Seren 0.1.29
Up Next from Nixgates Repo
Continuous Playback (All episodes in the picture, were auto played one after the other, never paused, or stopped. The first link worked every time)
I have heard other people having the same issue.

IMAGE: 
![07ad3df767cb7b4e137ef3a0a01c84b7-jpg](https://user-images.githubusercontent.com/30740511/52817536-0cd7a000-309c-11e9-82a5-78335a8cb7ff.jpg)

**Comment by RagnarLothbrok-Odin** [comment] 2019-02-14 21:08
Also, number 18 is marked as watched, but I have only just started it, and I am only 1minute21seconds in

**Comment by nixgates** [comment] 2019-02-15 12:08
I'm not sure what the issue with them playing back one after the other? That's by design.

In regards to your issue with being marked as watched before completing the item this has been identified and should be fixed in the next update.

Would you mind expanding on your initial issue?

**Comment by RagnarLothbrok-Odin** [comment] 2019-02-15 14:33
Sorry, it was not an issue, I was just stating my current setup, auto-playing is how I like it. I just wanted to give as much information about how I use Seren, so you could easily pinpoint the issue.

**Comment by cartersball** [comment] 2019-02-15 15:43
I have seen this issue as well. It appears that episodes are being logged multiple times into Trakt history. Say for instance you've watched every episode of a show. Normally, rewatching an episode you've watched in the past would not be logged in Trakt history on their website as you've already watched them all. With the 1.29 update I have noticed that old episodes of shows the kids watch regularly show up in history on the Trakt website even though the entire series had been watched years ago. Episodes of series we have not completely watched are also logged multiple times in the history on the Trakt website. This may or may not be related to the issue where episodes are marked as watched immediately as they are began.

All of this is no big deal for a user to manage on the Trakt website, but I wanted to explain a little further what I believe the OP is seeing.

**Comment by RagnarLothbrok-Odin** [comment] 2019-02-15 20:08
If you have already watched a programme, and then rewatch it, I believe the function is to remark it as watched, since you watched it again. I believe that is completely normal behavior.

**Comment by Mastacc** [comment] 2019-02-16 00:25
It's the same issue as this one 
Duplicate of #37 
1x16 finishes, 1x16 and 1x17 marked as watched then 1x17 finishes and 1x17 marked as watched again and x18 marked as watched

**Comment by nixgates** [comment] 2019-02-19 23:33
Please refer to the original issue for further information

**Closed by nixgates** 2019-02-19 23:33 UTC
