### ISSUE TITLE
Keyboard not opening when enable search history is checked

### ISSUE THREAD

**Issue by mophawka** [nixgates/plugin.video.seren#111] opened 2019-05-01 18:17 UTC
@nixgates when i enable search history in settings the keyboard no longer pops up when i search for tv or movie. if i uncheck it . it works fine. this searching while inside the add-on. not a widget or favourite. I am using Eminence 2.0 MOD. Seren 0.2.24 kodi 18

This is happening on windows kodi, fire tv, and nvidia shield.

Any ideas?

Thank you

**Comment by denimnani** [comment] 2019-05-02 23:31
This is very strange, for me is working fine.
Try other skin only to rule out if is skin related.

**Comment by nixgates** [comment] 2019-05-06 23:17
@mophawka could you please follow @denimnani advise and try using a different skin? 

I'm unable to re-create this issue

**Comment by mophawka** [comment] 2019-05-08 18:53
@nixgates sorry for the delayed response. been AFK for a bit. it most certainly is a skin issue. i'm just trying to understand what is changing when i tick enable search history and when i uncheck it to cause one to suppress the keyboard and other not. can't exactly present this to official kodi forum as they frown upon and do not/will not support unofficial add-ons. Thanks

**Comment by nixgates** [comment] 2019-05-09 02:49
@mophawka totally understand, 

I might be able to help you out if you wouldn't mind passing over a debug log?

**Comment by mophawka** [comment] 2019-05-09 08:13
@nixgates debug log attached. the resulting file was too large to use pastebin so i zipped it and attached it. Appreciate the help

[kodi.zip](https://github.com/nixgates/plugin.video.seren/files/3160974/kodi.zip)

**Comment by nixgates** [comment] 2019-07-16 06:17
@mophawka there was some changes to the way search works in the new update.

Has this fixed your issue?

**Comment by nixgates** [comment] 2019-07-29 03:13
Closing incident due to issue being caused by skin and user un-reachable

**Closed by nixgates** 2019-07-29 03:13 UTC
