### ISSUE TITLE
[BUG] Trakt database rebuild error

### ISSUE THREAD

**Issue by MikeTosen** [nixgates/plugin.video.seren#668] opened 2021-08-13 21:10 UTC
**Describe the bug**

When rebuilding trakt database from seren - tools - trakt sync tools - rebuild database, it fails.
This then intern causes a trakt database rebuild loop.
There seems to be quite a few foreign key constraint violations causing this failure - so might be specific series or movie causing this.
It started with the new version of seren 2.1.4 while still on kodi 18.9, tried completely removing seren and reinstalling it-same error
Then upgraded to kodi 19, reinstalled seren - same error

**Log**
https://paste.kodi.tv/ebitukoguk.kodi

**To Reproduce**

Steps to reproduce the behavior, for example:
1. Go to Seren
2. Click on Tools
3. Click on Trakt Sync Tools
4. Click on Rebuild Database
5. After the rebuild completes, it gives an error "There were issues when processing the synchronization with trakt"

**Expected behavior**

The sync with trakt should not fail, and it should not go into a rebuild database loop every few minutes.

**Environment**

 - Operating System : Ubutu 20.04.2 LTS (kernel linux 5.4.0-81-generic)
 - Kodi Version 19.1.0
 - Seren Version 2.1.4

**Comment by drinfernoo** [comment] 2021-08-13 22:19
Is this the same error that you're getting in #664, @rwarnmsn?

**Comment by MikeTosen** [comment] 2021-08-13 22:30
Read #664 and it is the same error.
You can force the error by rebuilding the trakt db instead of waiting for the loop, it would periodically try to rebuild the db, but i believe it is one and the same error.

**Comment by drinfernoo** [comment] 2021-08-14 11:07
This doesn't happen to us in testing, so I can't simply "force the error" that way, unfortunately.

**Comment by MikeTosen** [comment] 2021-08-14 12:52
Jip, I do realize, being a developer myself I appreciate the effort and dedication going into something like this.
With an error like this, that happens only yo certain people or certain scenarios can be a pain to chase down :-(

I times the rebuild loop on this machine - and it tries to rebuild the database exactly every 30 minutes.
So I waited till like a minute before it stated and I created a debug log of it - hope it sheds some more light on the subject.
From reading the log, I only see the same foreign key violation - exactly like when I trigger a database rebuild.
This runs every 30 minutes - same error every time.

[https://paste.kodi.tv/korihoxuqi.kodi](https://paste.kodi.tv/korihoxuqi.kodi)

**Comment by drinfernoo** [comment] 2021-08-14 14:25
Could you possibly upload your `traktSync.db` and `settings.xml` so we can try to replicate this issue?

We suspect it's down to some particular show in your account which is problematic on the Trakt side... but it would be very difficult to tell which show without your specific files.

**Comment by MikeTosen** [comment] 2021-08-14 14:41
No problem,  how can i send it privately,  don't want to put all that detail for public ?

**Comment by rwarnmsn** [comment] 2021-08-14 21:50
> Is this the same error that you're getting in #664, @rwarnmsn?

Yes, @drinfernoo, I believe it is.

**Comment by drinfernoo** [comment] 2021-08-15 01:29
If one of you guys could attach the files here, that'd be fine. If not, I'm available on Telegram and Discord as well.

**Comment by rwarnmsn** [comment] 2021-08-15 02:31
Where do I locate these files, @drinfernoo? I FTPed into my device but I'm not sure where to find them.

**Comment by rwarnmsn** [comment] 2021-08-15 03:08
@drinfernoo, may I email these files to you? (I unfortunately don't use either of those two platforms.)

**Comment by kaufman2000** [comment] 2021-08-15 10:49
I have this error. Here is my debug log after rebuilding the database

https://drive.google.com/file/d/1njhc1hbLXZC74pTc9ieTZSc4flS9gOCl/view?usp=sharing

**Comment by MikeTosen** [comment] 2021-08-15 11:40
> Could you possibly upload your `traktSync.db` and `settings.xml` so we can try to replicate this issue?
> 
> We suspect it's down to some particular show in your account which is problematic on the Trakt side... but it would be very difficult to tell which show without your specific files.

Just sent you a telegram with files requested,  also link to my drive.

**Comment by drinfernoo** [comment] 2021-08-16 12:39
So we're seeing the exact same thing as in this issue: https://github.com/nixgates/plugin.video.seren/issues/628#issuecomment-881732878

Basically, Trakt has malformed data on their server, in that it has *two* "Specials" seasons for the show "Street Outlaws: New Orleans". We've logged a support ticket with Trakt to try and get that resolved, but in the meantime, we want to recommend that everyone remove this show from your Collection, Watchlist, and Watched History. I know that is inconvenient, but it seems that (so far) only people with *that show* in their Trakt database are having an issue with the rebuild.

**Comment by MikeTosen** [comment] 2021-08-16 12:50
Great, thanks.
Just removed the show and watched history.
All working, db rebuilt successfully 👍

**Comment by drinfernoo** [comment] 2021-08-16 13:05
Moreover, it appears that the show is *only* listed in Trakt with bad data... TVDB (which is listed as the metadata source for that show) only lists one "Specials" season...

Perhaps if anyone reading this issue has Trakt VIP, they could attempt to "Refresh Data" on the Trakt listing?

**Comment by rwarnmsn** [comment] 2021-08-16 17:17
I also removed "Street Outlaws: New Orleans" from my Collection, Watchlist, and Watched History. The database was then rebuilt without issue and I saw the message, "Seren: Trakt / Database has been rebuilt", for the first time ever. Removing this show is a SMALL inconvenience to me. Thank you for researching this and for the fix!

**Comment by craigsblackie** [comment] 2021-08-17 09:52
I can confirm I have this issue to but have never watched, searched or heard of  "Street Outlaws: New Orleans". There is clearly some regression in this update. I'll upload some logs if I get the time.

**Comment by zambux** [comment] 2021-08-17 12:40
i don´t  have that show and having same problem.

**Comment by MikeTosen** [comment] 2021-08-17 14:05
Seems there is multiple shows with bad data in trakt db then, the reason this specific show was highlighted here, is that i sent my settings.xml and trakt.db file, and it turns out its this show in my case that is causing the problem. 
You can see it happen if you search for street outlaws new Orleans in seren, and just view the show details,  it fails right there, without watching or adding it to your collection.

**Comment by drinfernoo** [comment] 2021-08-17 14:54
Anyone else having "this issue" or "same problem" needs to upload a log file so we can verify that it is indeed the "same problem".

**Comment by zambux** [comment] 2021-08-17 15:13
https://paste.kodi.tv/cekebohemi.kodi

**Comment by drinfernoo** [comment] 2021-08-17 15:30
> https://paste.kodi.tv/kiyeyayadi.kodi

This is a completely different error, and more likely related to your network :wink:

**Comment by zambux** [comment] 2021-08-19 07:04
it as done it from de start of seren 2.x

**Comment by drinfernoo** [comment] 2021-08-19 13:06
@zambux You've been having this issue since January??

**Comment by zambux** [comment] 2021-08-19 15:49
yes

**Comment by drinfernoo** [comment] 2021-08-19 19:06
@zambux Your error isn't a Seren issue, from what I can tell from your previous log file.

It looks more like you're having a network error while trying to connect to Trakt, possibly due to a VPN or something.

For us to investigate further (if there even is any investigation for us to do), you'll need to open a separate issue from this one, as it isn't the same thing at all. Make sure to include a **full debug log** if you open a new issue.

**Comment by zambux** [comment] 2021-08-19 19:22
O dont use any VPN. Ok Will try to make full log

**Comment by kaufman2000** [comment] 2021-08-20 07:39
The Street Oulaws solution has cured the issue for me.

**Comment by drinfernoo** [comment] 2021-08-25 15:51
@aeolous73 Also bear in mind that (re)authorizing Trakt should automatically trigger a database rebuild, so you shouldn't need to start it manually.

**Comment by aeolous73** [comment] 2021-08-25 16:15
> @aeolous73 Also bear in mind that (re)authorizing Trakt should automatically trigger a database rebuild, so you shouldn't need to start it manually.

didnt do anything just (re)authorizing Trakt i had tried it a lot of times it only worked with the way i describied in my previous post.

**Comment by FloydHaddocks** [comment] 2021-08-28 00:29
@drinfernoo Sorry for the unnecessary question, checked Reddit & found "A history of Ancient Britain" - that was in my list so thanks very much, hopefully that's my issue sorted.

**Comment by theretohere** [comment] 2021-09-03 03:32
I was having the same issue, and removing the show "See" from a Trakt watchlist let the db connect/build/work again normally.

https://trakt.tv/shows/see#seasons

**Comment by drinfernoo** [comment] 2021-10-03 14:26
This should be fixed in 2.1.5, can you check?

**Comment by theretohere** [comment] 2021-10-04 03:01
"See" added to a watchlist and it did not break trakt in seren. This part looks good.

**Comment by drinfernoo** [comment] 2021-10-04 21:06
@MikeTosen, is this still an issue?

**Closed** 2021-11-16 15:19 UTC
Labels: bug, awaiting completion confirmation

**Comment by MikeTosen** [comment] 2021-11-16 15:26
Since removing the one show causing this, i have not had any issues, thanks
