### ISSUE TITLE
[BUG] TV shows won't play with the latest update 2.0.10

### ISSUE THREAD

**Issue by patel-jeel92** [nixgates/plugin.video.seren#380] opened 2021-01-08 04:02 UTC
**Describe the bug**
When attempting to play a tv show, the add-on just says Building list items, starting playback and doesn't proceed to play anything. It seems like it doesn't even scrape for anything. I am running kodi 18.9 on shield tv pro 

**To Reproduce**
1. Go to Discover TV Shows --> Trending
2. Click on The Mandalorian 
3. See error. It should eventually scrape for the tv show and then start playback

**Expected behavior**
Serena should build the playlist, identify any resume points, scrape for the source and then start playback

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 running on shield tv pro 
 - Version 2.0.10

**Log
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/5785142/kodi.log)

**Comment by nixgates** [comment] 2021-01-08 04:50
@patel-jeel92 please disable auto episode resume while we wait for the next update! Sorry it's been fixed and won't be long!

Duplicate of #373

**Closed by nixgates** 2021-01-08 04:50 UTC
Labels: bug, duplicate

**Comment by patel-jeel92** [comment] 2021-01-08 13:57
Just read through #373. Will wait for the next update. But wanted to ask, in the next update will it be fixed so we can use it as it's intended (Resuming automatically when you click a show) or will it just be set to off by default.

**Comment by nixgates** [comment] 2021-01-08 22:26
No its a solid fix :)

**Comment by quentin2118** [comment] 2021-01-15 04:25
Seren was working fine and suddenly it can't talk to trakt which means it can't be used at all because it will not populate any of the lists as far as shows or movies goes

**Comment by drinfernoo** [comment] 2021-01-15 04:51
Update to 2.0.11.
