### ISSUE TITLE
Seren  upgrade. 

### ISSUE THREAD

**Issue by Greg0059** [nixgates/plugin.video.seren#621] opened 2021-06-13 18:46 UTC
Seren was recently upgraded.  And now it been  showing messages across the the top off the screen  saying real debrid  premiere  has iexpired  but  when you go in seren it has not.  But you have to  redo any settings that you want  on seren  like color.  On playback  if you want tv shows on  select  instead  of auto and press OK and clear both of the Caches . Then back out of kodi go to your Firestick settings  and force stop kodi and clear cache.  Then go back to kodi and open seren and watch a movie or  a tv show .

**Comment by MichaelRPowell** [comment] 2021-06-14 04:05
Sounds like the same issue:
#619

**Comment by Greg0059** [comment] 2021-06-14 04:37
I am still getting  the message  every  few hours  . OK  so I just back out of kodi 19.1 matrix on my 4k Firestick go back in and open Seren clear both caches under tools.  I checked that read debrid  and Trakt  are still enabled and my my settings are the same as before.  Then go to movies and or TV shows.  And  check to see if they play OK and they  are.

**Comment by drinfernoo** [comment] 2021-06-14 05:10
Yes, duplicate of #619.

**Closed by drinfernoo** 2021-06-14 05:10 UTC
