### ISSUE TITLE
[BUG] 2.0.16 RD & PM Cloud Inspection Not Working For This Show Episode

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#478] opened 2021-01-25 20:35 UTC
**Describe the bug**
Charmed (2018) - Season 3 Episode 1 is not showing up in results as CLOUD under source type.  It doesn't seem like cloud inspection is working for this particular show episode for both RD and PM.  

**To Reproduce**
1. Add magnet to PM and/or RD cloud.  Magnet link is listed below.
2. search for the Charmed (2018) show
3. go to season 3
4. go to episode 1
5. let seren scrape for providers and cloud inspection
6. see the first link, the source type is not CLOUD (since i cached it to PM and RD cloud)

**Expected behavior**
The show that I cached in PM and RD should show up on top specified as CLOUD under cloud type.

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.16
 - Skin:  Arctic Horizon Official

Magnet Link:
magnet:?xt=urn:btih:64e38018e3dd2f6a55bf1292da4d9d83d4c58af3&dn=charmed 2018 s03e01 1080p web h264-cakes[eztv re]&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://retracker.lanta-net.ru:2710/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://ipv6.tracker.harry.lu:80/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://tracker.open-internet.nl:6969/announce&tr=udp://open.demonii.si:1337/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://denis.stalker.upeer.me:6969/announce&tr=udp://p4p.arenabg.com:1337/announce

**Comment by adiadi2** [comment] 2021-01-25 22:09
These are some examples of found (first two) and not found (last two) files from RD cloud, so obviously if there's anything between show title and SxxExx label, filename doesn't get recognised and it would be great if you can somehow filter out anything between parentheses in front of SxxExx  and 4 digit number from LoganWolverineX example "charmed.2018.s03e01.1080p.web.h264-cakes[eztv.re].mkv (2.18GB)"  from filename when scraping cloud sources for TVshow episode.
Otherwise thanks for the great addon.
And I have one more question well more like feature request, and thats to have fallback language or at least selectable language  for movie / TVshow titles, while it's nice to have localized content I would love to see german, italian, japanese... titles in english if not available in my native croatian. 

 
Scraped from RD
![Screenshot_20210125-134206_Chrome](https://user-images.githubusercontent.com/38987173/105765281-7df68200-5f58-11eb-84a3-88dbfba35464.jpg)
![Screenshot_20210125-134230_Chrome](https://user-images.githubusercontent.com/38987173/105765290-80f17280-5f58-11eb-9d28-828996bb3293.jpg)

Not sraped from RD
![Screenshot_20210125-134312_Chrome](https://user-images.githubusercontent.com/38987173/105765293-82bb3600-5f58-11eb-8abf-44ca165abec6.jpg)
![Screenshot_20210125-134543_Chrome](https://user-images.githubusercontent.com/38987173/105765299-85b62680-5f58-11eb-8bb6-65ada30485e9.jpg)

**Comment by LoganWolverineX** [comment] 2021-01-25 22:12
Looks like the pattern happens on “The Stand (2020)” too. I noticed that last week.

**Comment by tundrablasen** [comment] 2021-01-26 06:29
Having the same issue. My PM cloud files doesn’t get recognized anymore since 2.0.16

also noticed it with ´the Stand´, but also noticed it on many other shows and movies.

 It seems that v2 broke the cloud inspection. It was working flawlessly with v1

**Comment by LoganWolverineX** [comment] 2021-01-26 06:31
@tundrablasen cloud inspection still works for RD and PM. I only notice it not working for certain ones. Hopefully Nixgates is able to see why it’s not working for certain ones.

**Comment by tundrablasen** [comment] 2021-01-26 07:45
> @tundrablasen cloud inspection still works for RD and PM. I only notice it not working for certain ones. Hopefully Nixgates is able to see why it’s not working for certain ones.

Ofc I haven’t checked for all files available. But yes it not working always. Could be because of year as you mentioned. Could also be other reasons

**Comment by LoganWolverineX** [comment] 2021-01-26 20:41
here's another magnet for "Star Wars Clone Wars Series season 1 - 6 that didn't get scraped in cloud inspection for RD.

magnet:?xt=urn:btih:8ecf75f2673f18365b27afecaeca5ed70cb11ffa&dn=Star Wars The Clone Wars (Seasons 1-6 + Movie) (High Quality)(Tri Audio) [1080p] Blu-Ray Rip&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=http://tracker.opentrackr.org:1337/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://p4p.arenabg.ch:1337/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=udp://tracker.ilibr.org:6969/announce&tr=udp://explodie.org:6969/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=udp://eddie4.nl:6969/announce&tr=http://anidex.moe:6969/announce&tr=http://tracker.anirena.com:80/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce

Here's an example of how the files are named.
![Screenshot_20210126-154118_TorrSE](https://user-images.githubusercontent.com/67085646/105902697-fc9cff00-5fec-11eb-9bee-a8bb35190d7f.jpg)

**Comment by nixgates** [comment] 2021-02-01 04:58
Fixed for next update! let me know if you still have issues after it's released

**Comment by LoganWolverineX** [comment] 2021-02-01 05:00
@nixgates thanks a lot man! Appreciate this fix!  Will check it out once it’s out.

**Comment by tundrablasen** [comment] 2021-02-11 19:34
@nixgates @LoganWolverineX 

I found another bug, which seems not to be related to YEAR Date in the filename. But maybe because its a Season Pack Torrent?

**Cloud Inspection is failing in the following case as well:**

MasterChef.US.S06.1080p.HULU.WEBRip.AAC2.0.x264-QOQ[rartv]

> magnet:?xt=urn:btih:36306290f8207366bc0370af2909c9080bda7135&dn=MasterChef.US.S06.1080p.HULU.WEBRip.AAC2.0.x264-QOQ%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730&tr=udp%3A%2F%2F9.rarbg.to%3A2930

MasterChef.US.S07.1080p.HULU.WEBRip.AAC2.0.x264-QOQ[rartv]
magnet:?xt=urn:btih:f1d80fe7186650762e947a785efca2696ffe8acf&dn=MasterChef.US.S07.1080p.HULU.WEBRip.AAC2.0.x264-QOQ%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2840&tr=udp%3A%2F%2F9.rarbg.to%3A2890


MasterChef.US.S08.1080p.HULU.WEBRip.AAC2.0.x264-AJP69[rartv]
magnet:?xt=urn:btih:a2cfd41f755c26c2f12dc42960e5302c8d5d8f7e&dn=MasterChef.US.S08.1080p.HULU.WEBRip.AAC2.0.x264-AJP69%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2740&tr=udp%3A%2F%2F9.rarbg.to%3A2720


Masterchef.US.S09.720p.AMZN.WEBRip.DDP2.0.x264-NTb[rartv]
magnet:?xt=urn:btih:0ffa167be8288b689507c4632965d3561e075203&dn=Masterchef.US.S09.720p.AMZN.WEBRip.DDP2.0.x264-NTb%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2820&tr=udp%3A%2F%2F9.rarbg.to%3A2880


MasterChef.US.S10.1080p.AMZN.WEBRip.DDP2.0.x264-AJP69[rartv]
magnet:?xt=urn:btih:55d7ef507feaf56589b766bbe52496c33ac5dd11&dn=MasterChef.US.S10.1080p.AMZN.WEBRip.DDP2.0.x264-AJP69%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730&tr=udp%3A%2F%2F9.rarbg.to%3A2720

Files are cached in the Premiumize Cloud, but when searching with Seren 2.0.16, cloud inspections fails

![2021-02-11 20_31_05-Premiumize me, All in One Cloud-Downloading - Brave](https://user-images.githubusercontent.com/46343142/107688626-25d5b480-6ca8-11eb-959c-8bff1e0a2b5b.png)


**To Reproduce**
Steps to reproduce the behavior:

1. Add magnet to PM and/or RD cloud. Magnet link is listed above.
2. search for the Masterchef US show
3. go to season and episodes
4. let seren scrape for providers and cloud inspection
5. see the first link, the source type is not CLOUD (since i cached it to PM cloud)

**Expected behavior**
The show that I cached in PM and RD should show up on top specified as CLOUD under cloud type.

Kodi Version (please complete the following information):

Kodi Version 18.9
Seren Version 2.0.16
Skin: Estuary Mod v2

**Comment by adiadi2** [comment] 2021-02-16 16:55
Hi, one more non working example (spaces in filename)

![Slika zaslona s 2021-02-16 17-52-01](https://user-images.githubusercontent.com/38987173/108095291-fd6f0100-707f-11eb-9314-a596d92bb827.png)


regards

**Comment by drinfernoo** [comment] 2021-03-18 21:13
This should be fixed in 2.0.17.

**Closed by drinfernoo** 2021-03-18 21:13 UTC
Labels: awaiting update, bug
