### ISSUE TITLE
[BUG] Trakt Rating dialog won't pop up after movies only tv shows

### ISSUE THREAD

**Issue by supragtr2002** [nixgates/plugin.video.seren#617] opened 2021-06-05 21:35 UTC
**Logs**
[Kodi Log](https://paste.kodi.tv/huhusafozi) 

**Describe the bug** 

In Kodi 19 and the Trakt rating pop up will only appear at end of TV Show episodes but not after movies. Have scrobbling enabled in both seren in trakt.script if I disable it in either the Rating pop up doesn't come up at all. 

**To Reproduce**
When a movie has finished the Trakt pop up rating does not come up. 

**Expected behavior** 

Expcting the Rating to Pop after playing movies and tv shows. 

**Screenshots**
N/A 

**Kodi Version (please complete the following information):** 

Kodi Version 19.0
Seren Version 2.0.18+Matrix. 1
Additional context
N/A

**Comment by drinfernoo** [comment] 2021-06-18 18:55
That's odd... I have the opposite behavior. It is only working for me for movies, but not for episodes 🤔

**Comment by Dealz-416LS** [comment] 2021-06-18 20:24
I reported this a while back, I actually stopped using Trakt.Script due to the weird and inconsistent interactions with Seren when it got updated to 2.0

Maybe I'll try/test it again since both addons have been updated quite a bit.

[Question/Issue: Seren Trakt vs Trakt.Script Add-on](https://github.com/nixgates/plugin.video.seren/issues/522)

I had previously ran the issue by the dev of Trakt.Script and the issue looks to be because the Trakt.Script `resources.lib.scrobbler` is not getting a title of the movie, only the year.

More details in the link below.

[[BUG] Trakt rating dialog not being displayed for movies.](https://github.com/nixgates/plugin.video.seren/issues/440)

**Comment by drinfernoo** [comment] 2021-06-21 12:22
I believe we have actually fixed this one in an upcoming update, finally!

**Comment by drinfernoo** [comment] 2021-07-02 02:18
This one should be fixed as of 2.1.2.

**Comment by StanLee01** [comment] 2021-07-04 19:18
So do we still need to disable one of the scrobbling settings (seren or trakt add-on) to make ratings pop-up (and to scrobble everything you watch)? I didn't get any pop-up with the new update. I have both scrobbling options enabled (seren and trakt add-on).

**Comment by drinfernoo** [comment] 2021-07-04 20:40
You shouldn't have to, as we removed that check, and are sending the IDs regardless. Do you have ratings turned in the Trakt add-on?

**Comment by StanLee01** [comment] 2021-07-04 20:44
> You shouldn't have to, as we removed that check, and are sending the IDs regardless. Do you have ratings turned in the Trakt add-on?
I see where it went wrong. I was watching a show and after that episode next-up scraped the next episode and the source selection page came up. But after that episode I stopped watching, and the ratings pop-up worked. So so far TV shows is working. Didn't try movies yet.

**Comment by Dealz-416LS** [comment] 2021-07-04 21:47
@StanLee01 @drinfernoo 

After seeing the comment by @drinfernoo that Seren now sends the IDs regardless I reinstalled the Trakt.Script Add-on to run some tests.

So far I can confirm that if you have Seren Trakt scrobbling turned on, but disable the scrobbling in Trakt.Script Add-on for both Shows and Movie items...

1. Scrobbling still works.
2. Successfully marks as watched.
3. Rating dialog appears.

Everything is looking good! Seren and Trakt.Script no longer have a weird relationship lol.

**Comment by drinfernoo** [comment] 2021-07-05 00:04
Great to get a confirmation 🎉

**Closed** 2021-07-05 00:04 UTC
Labels: awaiting completion confirmation, bug
