### ISSUE TITLE
[BUG] Xbox Series X won't fully sync with Trakt.

### ISSUE THREAD

**Issue by McPoon** [nixgates/plugin.video.seren#418] opened 2021-01-15 17:15 UTC
**Logs**

https://paste.kodi.tv/uyulovubun

**Describe the bug**
When starting kodi, trakt starts to sync like earlier versions, as well as during shows/movies. Also Next Up and recently watched don't work any more. Still testing other features. 

**Kodi Version (please complete the following information):**
 - Updated to newest, 2.0.12

**Comment by McPoon** [comment] 2021-01-16 17:06
As of 2.0.13, nothing has changed for me. Still an error when syncing with Trakt and I can't access Next Up or Recently Watched.

**Comment by 101ben1011** [comment] 2021-01-17 12:24
I have the same issue on series x, since seren 2.0. Trakt either won't authorise properly without an error, or occasionally if I dont get the error message, my tv collection is still empty due to not syncing properly, then later I will find my trakt account has disappeared from the accounts page. I end up disabling seren and retrying when it updates again to try and avoid the trakt overload issues from before.
I know nixgates has been working on trying to nail down the xbox bugs.

**Comment by 101ben1011** [comment] 2021-01-17 12:44
Actually,my trakt account seems to authorise ok now on 2.0.13 with no errors, but my tv collection is still a blank page.
If I try and clear metadata and rebuild the trakt database, it throws up a seren error about the trakt synchronisation.
This is a log file just after the sync error:

https://paste.kodi.tv/socaqederu

Regards,
Ben

**Comment by nixgates** [comment] 2021-01-20 22:13
@McPoon @101ben1011 please follow this on the main bug already raised for this. #274

This has been addressed and will be available in the next update :+1:

**Comment by nixgates** [comment] 2021-01-22 01:48
@McPoon I'm gonna close this one off. Appears to be a duplicate of issue #365 and there's a lot more information to follow along with over there :)

**Closed by nixgates** 2021-01-22 01:48 UTC
Labels: awaiting update, bug
