### ISSUE TITLE
[REQUEST] Icons implantation with download pack from Auramod

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nixgates/plugin.video.seren#557] opened 2021-03-17 22:30 UTC
**Is your feature request related to a problem? Please describe.**
This is related to an icon bug that happened when you released Seren 2.0 which basically got rid of the icons from Auramod.

**Describe the solution you'd like**
A Solution i would like is for you to download this pack of Seren Icons from Auramod and implant them to seren so its not the same icon every time.
https://www.mediafire.com/file/94lw7zjhj7ag815/Seren_Icons_from_Auramod.zip/file

**Describe alternatives you've considered**
Moving back to the last release of Seren 1.0 or waiting for this next update soon.
https://www.reddit.com/r/Addons4Kodi/comments/kyfoy6/seren_genre_icons/

**Additional context**
If these icons are not really the icons your looking for, i perfectly understand and i will send more alternatives or wait for the next release soon.

**Comment by drinfernoo** [comment] 2021-03-18 21:59
The icons not being "correct" in AuraMOD is actually an AuraMOD bug, as it is using paths that aren't valid anymore. The skin needs to be updated.

**Comment by Goldenfreddy0703** [comment] 2021-03-18 22:28
Actually, its not AuraMod im talking about, its about the implantation for seren, You see Fen, Exodus, Yoda, and other addons have icons but you don't see seren which is why seren does not have any icons which is why i got the downloadable icons from Auramod thanks to SerpentDrago who was a beta tester of seren back then when it was in alpha. There has been so many request for this but they have been rejected by the wrong reasons.

**Comment by Goldenfreddy0703** [comment] 2021-03-18 22:30
Again, Seren should just include icons / images by default instead of leaving it aside.

**Comment by SerpentDrago** [comment] 2021-03-21 20:58
> The icons not being "correct" in AuraMOD is actually an AuraMOD bug, as it is using paths that aren't valid anymore. The skin needs to be updated.

kinda wrong way to look at it man . 

The issue is seren is not including the icons at all , currently seren has no icons . so some skins like auramod had a "hack" to at least make it work . that hack was broken by seren changing paths yes . 

The real solution is for Seren to actually include icons . 

I'd like to request this get reopened . The reference of auramod was only a example . the request is for icons in seren .

**Comment by Goldenfreddy0703** [comment] 2021-03-22 02:32
Thank you and your right. Sorry for taking myself too far on this issue.

**Comment by Goldenfreddy0703** [comment] 2021-05-21 05:22
Umm....This wont be closed right? 
Could this be pinned pls?

**Comment by Goldenfreddy0703** [comment] 2021-05-21 05:23
oh yay, its not stale anymore, im happy

**Comment by Goldenfreddy0703** [comment] 2021-07-20 09:17
No it's not stale lol.

**Comment by Goldenfreddy0703** [comment] 2021-07-20 09:18
Remove the stale please. 😂

**Comment by Goldenfreddy0703** [comment] 2021-07-20 09:19
Yay

**Comment by drinfernoo** [comment] 2021-07-30 04:19
For the next update, we have finally implemented not only genre icons, but a "Next page" icon 🎉

**Comment by Goldenfreddy0703** [comment] 2021-07-30 13:09
Nice I'm so happy to hear that. Thank you so much.

**Comment by drinfernoo** [comment] 2021-08-05 13:29
This one should now be fixed in 2.1.4. Would you be able to confirm the icons are showing for you now?

**Comment by Goldenfreddy0703** [comment] 2021-08-06 16:08
Hey I'm sorry I was busy yesterday but icons are not showing for me when I updated to seren 2.1.4.
![Screenshot_20210806-120635_Kodi.jpg](https://user-images.githubusercontent.com/62456796/128539804-8572481e-5b32-4817-8865-6d7476a92cf1.jpg)

**Comment by Goldenfreddy0703** [comment] 2021-08-06 16:13
Hey wait a sec, I'm sorry i can confirm. That icons are in genres and next page. 

![Screenshot_20210806-121142_Kodi.jpg](https://user-images.githubusercontent.com/62456796/128540380-bad0333b-4855-4227-bd36-c7dc90f09250.jpg)
![Screenshot_20210806-121125_Kodi.jpg](https://user-images.githubusercontent.com/62456796/128540395-af30e713-d1b9-4b16-85a2-6f620302c82d.jpg)

**Closed** 2021-08-06 17:46 UTC
Labels: enhancement
