### ISSUE TITLE
Does not select the chosen option and rolls over the remaining till it say no source found.

### ISSUE THREAD

**Issue by ozooha** [nixgates/plugin.video.seren#541] opened 2021-03-04 17:35 UTC
**Logs**

See the debug logs to assist with your issue:
`
[kodi_seren.log](https://github.com/nixgates/plugin.video.seren/files/6085546/kodi_seren.log)
`

**Describe the bug**
Upon selecting a show from Trakt and manually selecting a link, it instead of playing the link continues to go through all the torrent links one after the other till it says that it cannot find any watchable source. In fact the source works as they are observed to be cached on real-debrid (among the others which it went through) since I can play them fine through the "my files" options in the menu. 

**Kodi :**
 - Kodi Version 19.0

**Comment by newf276** [comment] 2021-03-05 03:19
Hi I had same issue, but I was using Libreelec version of Matrix. I read somewhere to fix the skipping all sources from RD I had to replace a line in:
go to folder for plugin.video.seren / Resources / lib / Debrid
Then open real_debrid.py with Notepad and change the line:
from json.decoder import JSONDecodeError
with
from simplejson.errors import JSONDecodeError
Save the change and reboot for the change to take effect.
Or you can just install my edit located on my GitHub. Hope it solves your issue, it has worked for many others.
https://github.com/newf276/newf276.github.io/raw/master/zips/plugin.video.seren/plugin.video.seren-2.0.16%2Bmatrix.1.zip

**Comment by fjen** [comment] 2021-03-05 15:10
duplicate of #487

**Comment by drinfernoo** [comment] 2021-03-05 15:45
@fjen Agreed.

**Closed** 2021-03-05 15:45 UTC
Labels: bug
