### ISSUE TITLE
Auto Resume for Shows not playing next episode

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#56] opened 2019-02-19 22:57 UTC
Auto Resume for Shows is not loading the next episode if the last one was fully watched.

Should it not resume the episode if we didn't finish it and if we did load the next one.

The last episode you have watched is loaded even if you have it marked as watched.

Is it possible to make it load the next episode and not the previous one.

Thank you

**Comment by nixgates** [comment] 2019-02-20 00:11
Sorry I'm having a bit of trouble understanding this so let me just confirm I have this right.

Autosume is starting from the last watched episode even if the episode was completed?

**Comment by Mastacc** [comment] 2019-02-20 01:48
I don't know what he means, but sometimes Next Up doesn't show the next episode even though the one that is currently shown is marked watched. Even if you reload Kodi it stays like that until a lot of time has passed. Not sure if this is the same problem.

**Comment by icpryde** [comment] 2019-02-20 04:50
It usually just takes a few minutes after the episode is watched then it will uodate and show the next episode. This feature is working as intended for me but I guess if it updated faster thst would be cool but  doesn’t change anything

**Comment by mophawka** [comment] 2019-02-20 10:15
> I don't know what he means, but sometimes Next Up doesn't show the next episode even though the one that is currently shown is marked watched. Even if you reload Kodi it stays like that until a lot of time has passed. Not sure if this is the same problem.

sounds like a trakt sync issue and not a seren issue.  try and reauth your trakt and try again? also make sure you are not running another trakt addon along with seren. i've had this issue and it was a conflict but it was on my end. What you describe its instant for me. if another episode exits it shows up right away in next up after i refresh the content.

**Comment by lukehansford** [comment] 2019-02-20 15:33
> Sorry I'm having a bit of trouble understanding this so let me just confirm I have this right.
> 
> Autosume is starting from the last watched episode even if the episode was completed?

Yes when you go to the trending, most watched or trakt collections and click on any movie or TV show it will try and auto resume if you have the option selected in the settings.

What it is doing is starting from the last watched episode even if you have already completed it.

say your on episode 5 of a tv show and you have watched until epsiode 4 100% it will still load episode 4 and not episode 5 as it should do.

hope that clarify's the issue and a fix can be made so it will play the same episode as in the up next section.

this is really useful because we can use the unfinished shows in widgets and just click on the show and it will go to the episode and the same for trending sections. if we have not watched the show it will start from episode 1. if we have it will play the next episode and if we have stopped half way through an episode it should resume at that point from the trakt bookmark.

thankyou

**Comment by nixgates** [comment] 2019-02-21 04:10
Are you perhaps running the trakt add-on as well as Seren's trakt scrobbling?

If you are, can you try disabling one  (the trakt add-on or the setting in Seren) and re-test?

**Comment by lukehansford** [comment] 2019-02-21 13:54
I do not have the Trakt add-on installed.

When you go to your Trakt collection and click on a show it will load the last watched episode and not the next up one.

I have tested on may shows where I am on different episodes.

Example I click the magicians TV show in my Trakt collection and in Seren up next I have episode 5 to watch but it auto resumes to episode 4.

Some with others.

**Comment by nixgates** [comment] 2019-03-01 03:42
I'm looking it this right now, sorry the delay.

**Comment by lukehansford** [comment] 2019-03-01 16:53
To clarify. I only want the auto resume to play the next unwatched episode. The same episode number in the Next Up section. 

It is currently a bug where it will only play the last watched episode which is pretty useless.

**Comment by nixgates** [comment] 2019-04-10 00:17
This issue was due to Kodi not advising Seren on playback finished. 

This should be fixed in next public update.

**Comment by nixgates** [comment] 2019-04-16 01:59
@lukehansford 

Can you please check and advises if the issue has been rectified?

**Comment by nixgates** [comment] 2019-04-28 23:20
Closing issue, this should have been rectified in a earlier release.

Please let me know if this is not the case

**Closed by nixgates** 2019-04-28 23:20 UTC
Labels: awaiting update, bug
