### ISSUE TITLE
[BUG] Next Up not working 100%

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#872] opened 2022-12-30 13:45 UTC
Small bug in the Next Up system. Sometimes it doesn't work as intended. Not all the time, but from the "Next Up" section, I just started an episode, and at the end of it, it did not pop up with Next Up, nor did pressing >> (next) on the player keys make it go to next episode.
I copied this log file right after this happened this time, seen it one or two times before but didn't think anything of it, but now it's an upwards trend on it happening I think.
The next episode does have sources and everything, just started that one manually.
Kodi V 19.4
Seren 3.0.0
Windows 10

https://logpaste.com/r9a4IIwF

**Comment by TapMeDead** [comment] 2022-12-30 14:08
Some random thoughts, did I see the a4k scrapers being updated today at some point? could this be a factor?
Also, I upgraded the a4k scraper a few days ago, but did not delete the old a4k in there, should I do that or not? 
![Screenshot_1](https://user-images.githubusercontent.com/99356645/210078925-28c9ca31-4cce-4d0c-a168-c9f99e8cb2ac.png)

**Comment by cgwprs** [comment] 2022-12-30 14:30
I could see having two versions of the a4kscraper causing issues with Seren because of the way it scrapes different domains changes over time. I don't know that this would cause any issue with Next Up, but I will look into it, to see if I can contribute.

**Comment by TapMeDead** [comment] 2022-12-30 15:55
Update, I watched 4 more episodes via the Next Up section, and none of them activated Next Up to go to next episode on the list from there.

**Comment by drinfernoo** [comment] 2022-12-30 16:35
@TapMeDead You are watching shows that have more episodes available, right? Not ones that have just come out and have no further episodes to watch yet?

**Comment by TapMeDead** [comment] 2022-12-30 16:37
@drinfernoo Watching through the Next Up section where new episodes come up every day. 
So yes and no heh, but usually Seren will create a playlist off of the Next Up page, it just didn't today, and a few times yesterday.

**Comment by TapMeDead** [comment] 2022-12-30 17:01
@drinfernoo How ever, I just watched an episode from a season window, first ep of 4 available, and Next Up did not work here either.
New Log of that:
https://logpaste.com/aB4UWP0V

**Comment by drinfernoo** [comment] 2022-12-30 18:06
What I mean is, the shows you are choosing *from* Next Up, are they shows with more episodes for you to watch (i.e. shows that are finished and you're "catching up on"), or shows that have no new episodes after the current (i.e. "continuing" shows which you are caught up on)? 

If they have no more aired episodes available, then no playlist will be built.

**Comment by TapMeDead** [comment] 2022-12-30 18:17
@drinfernoo It has always, for as long as I've used Seren worked to, as you say it, catch up on recently aired episodes, through the Next Up window in shows. It would just cache the next episode, from the next show on that list. I always thought the cool thing about the Next Up system, was that it creates a list out of the current window, be in Next Up, or in a season window.
All I know is, it doesn't work as it has just a few days ago heh

**Comment by drinfernoo** [comment] 2022-12-30 18:54
Can you give an example of content that *does* have future episodes to build a playlist with, that *doesn't* end up showing you the Playing Next dialog?

I'm having trouble discerning in which situation you're saying it's not building playlists.

**Comment by TapMeDead** [comment] 2022-12-30 19:01
@drinfernoo That would be the first two log files upthere :)
In the Next Up window, all my shows that have aired episodes today will collect, right.
If I click the first episode up top, it will find sources for it, and start playing. Then once that episode is over, usually the Play Next popup will come up, and will want to play the next item from my Next Up window. This does not always happen anymore, the Play Next popup does not come up, and nothing is cached as intended. My log files should be old enough that you can see how it usually behaves, and compare to today :)

**Comment by TapMeDead** [comment] 2022-12-30 19:03
I can how ever confirm that it seems to work as usual if I am in a season window binge watching. Play Next pops up as intended here right now.

**Comment by drinfernoo** [comment] 2022-12-30 19:34
For now, I'm unable to reproduce this.

Steps I took to attempt to reproduce:

1. Ensure that both "Enable Smart Play" and "Enable Playing Next Dialog" are checked in the "Playback" section of Seren's settings
2. Search for show in Seren (I tested with Steven Universe, which has episodes ~11min long)
3. Pick an episode early on the series (I chose S01E01 to start)
4. Watch or skip to near the end (with <= 30 seconds remaining by default)
5. See the "Playing Next" dialog pop up, displaying the next episode in the playlist

You can also check throughout this process whether or not the playlist has been built by viewing the items in your playlist during playback.

In contrast, I chose the last episode of the series (S05E28) as another test, and as there are no further episodes after it, the dialog does not show up.

**Comment by drinfernoo** [comment] 2022-12-30 19:35
> Some random thoughts, did I see the a4k scrapers being updated today at some point? could this be a factor? Also, I upgraded the a4k scraper a few days ago, but did not delete the old a4k in there, should I do that or not? ![Screenshot_1](https://user-images.githubusercontent.com/99356645/210078925-28c9ca31-4cce-4d0c-a168-c9f99e8cb2ac.png)

This seems inconsequential. You have two different provider packages installed, not two versions of the same one. In any case, providers should not affect the building of playlists or the dialogs shown during playback.

**Comment by drinfernoo** [comment] 2022-12-30 19:47
As an example, in your log:

`2022-12-30 13:39:57.823 T:18976    INFO <general>: SEREN (6): Seren, Running Path - {'action': 'getSources', 'action_args': {'mediatype': 'episode', 'trakt_id': 6789853, 'trakt_season_id': 304422, 'trakt_show_id': 153528}}`

This is `The Mosquito Coast S02E09`. As of the time of this issue, that is the latest episode (https://trakt.tv/shows/the-mosquito-coast/seasons/2/episodes/9), having aired 12/29/22, so there will be no future episodes with which to build a playlist.

I've also found `Mythic Quest S03E09`, `Echo 3 S01E08` and `Slow Horses S02E06`.

All of these are the latest episodes at this time. The dialog should not be shown if there are no future episodes available. This is working as intended.

**Closed by drinfernoo** 2022-12-30 19:47 UTC
Labels: bug, unreproducible

**Comment by TapMeDead** [comment] 2023-01-05 15:11
@drinfernoo 
You are wrong, and I have to ask, do you actually use Seren to watch your episodes from Next Up?
Because then you would know that for as long back as I recall, if you started an episode In the Next Up window, the Play Next would create a playlist out of the Next Up list, and Play Next would work just fine, starting the next episode of the next show on the Next Up list.
This stopped working in 3.0.0, and now we have to manually close video, pick next show in Next Up and this gets tedious pretty fast when we watch a lot of shows in this window..
Ask Nix about this before you answer me again please, I know I had some lingo confused explaining this, but its a bug when something stops working as it has for year(s) :) 
![Screenshot_3](https://user-images.githubusercontent.com/99356645/210812814-7997dd0e-588f-4992-b2e8-52577159b3aa.png)

![Screenshot_4](https://user-images.githubusercontent.com/99356645/210812851-29ab9e54-d192-46ec-84c5-c421026b7413.png)

**Comment by cgwprs** [comment] 2023-01-05 15:24
This issue is still confusing me. Is Seren using the no longer maintained addon-on "Next Up" embedded into Seren? I thought that maybe it was embedding "Up Next" (currently maintained fork of Next Up) but that community thinks Seren has its own code for the "Next Up" feature. It seems quite odd that I am getting the same issue in two separate add-ons. Even adding the current version of Up Next to Kodi directly, does not fix the problem. Now I feel like I need to actually look at the code.
