### ISSUE TITLE
[BUG] Python 3 compatibility - fetching sources

### ISSUE THREAD

**Issue by Robinjoeh** [nixgates/plugin.video.seren#448] opened 2021-01-20 21:24 UTC
**Logs**

2021-01-20 23:16:03.634 T:12896   DEBUG <general>: SEREN: Processing Time -  13281ms - getSources
2021-01-20 23:16:03.634 T:12896   DEBUG <general>: 

2021-01-20 23:16:03.651 T:12896   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'TypeError'>
Error Contents: cannot pickle 'dict_values' object
Traceback (most recent call last):
 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 19, in <module>
   router.dispatch(g.REQUEST_PARAMS)
 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 146, in dispatch
   sources = helpers.SourcesHelper().get_sources(
 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/database/cache/__init__.py", line 468, in _decorated
   fresh_result = func(*args, **kwargs)
 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/helpers.py", line 57, in get_sources
   sources = Sources(item_information).get_sources()
 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/getSources.py", line 166, in get_sources
   return self._finalise_results()
 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/getSources.py", line 223, in _finalise_results
   sorted_sources = SourceSorter(self.media_type).sort_sources(
 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/source_sorter.py", line 247, in sort_sources
   self.torrent_list = deepcopy(torrents)
 File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/copy.py", line 161, in deepcopy
   rv = reductor(4)
TypeError: cannot pickle 'dict_values' object
-->End of Python script error report<--

**Describe the bug**
Decided to take Seren for a spin on Kodi 19, and just wanted to share some feedback.

Everything seems to work great, the only thing I noticed was this in the Kodi error log. When you are looking for new sources, the error appears in the log, which also prevents playback of the item.

Great work with Seren!

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0rc1

**Comment by nixgates** [comment] 2021-01-20 22:10
duplicate of #443 Fixed awaiting incoming update in the next few hours

**Closed by nixgates** 2021-01-20 22:10 UTC
Labels: bug
