### ISSUE TITLE
[BUG] Next Up Popup not coming up since last night or so

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#832] opened 2022-10-31 00:15 UTC
**Describe the bug**
Since last night, Next Up popup does not come up at the end of episodes, it does work if you scroll to the end, but the popup does not come up as it's supposed to.

**To Reproduce**
1. Watch episodes of shows with more than one unwatched episode
2. Wait till the end at the time you set in settings for the popup to come up, 1 min in my case
3. Watch as the popup does not come up

**Expected behavior**
Popup should come up so we can click Next

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 19.4
 - Version 2.2.2

**Additional context**
So far I have only seen this happen with the show "The Devil's Hour" -but I will see later if it happens in other shows as well, am binge watching this show right now, the bug happened on the first 4 episodes so far.

**Comment by TapMeDead** [comment] 2022-10-31 16:33
Kodi.txt log file here. I cleared the txt file first, then started episode 1 of Last Week Tonight and let it run to the end, where no Next Up popup showed up at 1 min before end as supposed to.
Then I let the episode run out completely, and Next Up did cache next episode in the background and put me in source select as it should for this test.
View the log of that here: https://logpaste.com/NVAUMe5F

**Comment by drinfernoo** [comment] 2022-10-31 18:43
@TapMeDead Appreciate the log, but I am going to close this one as duplicate of #829.

**Comment by drinfernoo** [comment] 2022-11-01 03:19
I know that for some reason, you have an aversion to sharing logs, but there is legitimately information contained in the log *file* that helps us out.

Can you please share a **full** debug log, rather than a snippet?

**Comment by TapMeDead** [comment] 2022-11-01 06:37
@drinfernoo That is a full log of what happens, I just did what I told in the post above. I didn't snippet anything, other than clearing 10 months of log before I started the first episode.
I did not clear it to hide anything, I don't have such aversion lol
But I can let it run for some hours today watching my shows, then upload it later with everything in it still.

**Comment by TapMeDead** [comment] 2022-11-01 10:04
Watched some shows, here's the log.
I Let all episodes I watched run to the end by themselves, no popup but things are getting cached in the background and I pop to source select on the next episode that way. None of the episodes where I was in the season window and started watching, got set as watched on Trakt. But, the last thing I watched was The Good Doctor, from the Next Up window in Shows, that episode got set as watched on Trakt. Maybe a clue there?
https://logpaste.com/Vdq8Jv8x

**Comment by whambulancePilot** [comment] 2022-11-02 10:18
I don't think this is a problem with Seren. Seren gets the TotalTime for each stream straight from Kodi's xbmc.Player() . The problem is that some streams can report an incorrect duration, so if you have your `Playing Next Dialog` set to pop up at 60 seconds before it ends, you can't actually reach that point on some streams. If you increase this to 180 seconds as a test, I bet it would show up on these problematic shows/episodes.

Here is an example of what I'm talking about:
![paste](https://user-images.githubusercontent.com/105106445/199464114-f5ef59e8-3edd-4f64-b616-acf03b4bc2f4.png)
^^ This is Kodi's duration.
![paste (1)](https://user-images.githubusercontent.com/105106445/199464245-ffb53522-d80b-48a9-8417-d5dbef726e0c.png)
^^ This is Media Player Classic's duration when I downloaded the file on PC and played it locally.

I streamed and then downloaded the exact same HDR release from SMURF. As you can see, I would never be able to reach -60 seconds on that stream with Kodi, hence no `Playing Next Dialog`.

**Comment by MikeTosen** [comment] 2022-11-02 16:28
Also getting this.
It happens on all my shows, so don't think it's a miss reported duration issue, unless all shows is all of a sudden miss reporting the duration.

**Comment by nutstool** [comment] 2022-11-02 19:47
I've also been experiencing this issue for the last few days. Next up not appearing at all. Most TV episodes also not being marked as watched in trakt but some are.

**Comment by drinfernoo** [comment] 2022-11-02 23:40
We think we've got a fix incoming soon!

**Comment by drinfernoo** [comment] 2022-11-02 23:55
This should be fixed in 2.2.3 :ok_hand:

**Comment by AnthonyA1223** [comment] 2022-11-03 17:45
> This should be fixed in 2.2.3 👌

Confirmed, fixed this issue and #829 with 2.2.3 

Thanks!

**Closed** 2022-11-04 03:34 UTC
Labels: bug

**Comment by TapMeDead** [comment] 2022-11-07 21:10
@drinfernoo 
After some extensive testing and binge watching, both issues seem to have been resolved and everything works as intended again.
Thanks for the help, and I am still a little sorry about the burst-out in the other thread, I appreciate all your hard work here.
