### ISSUE TITLE
[BUG] Seren not Auto Deleting R.D Torrents after 2.1.1 Update

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#634] opened 2021-06-21 00:15 UTC
**Describe the bug**
Seren is not Auto deleting torrents from R.D cloud when clicking any links in Source Select from Movies or TV Show Episodes.

**To Reproduce**
1. Go to 'Any Movie or TV Show Episode'
2. Click on 'Any link from Source Select from Real-Debrid'
3. Go to 'Real-Debrid, Log-In, Torrents tab'
4. See issue (Links clicked via Source Select from Seren stays in Torrent tab and NOT deleted)

**Expected behavior**
Prior 2.1.1 build, in Seren's settings, accounts, Real-Debrid having the option of **Auto Delete Torrents** enabled usually keeps the Torrent tab clean in Real-Debrid by Seren auto deleting any links you click to stream via Source Select within Seren.

**Screenshots**
![image](https://user-images.githubusercontent.com/76958541/122693953-dda44100-d209-11eb-90b1-b20142c69c50.jpeg)

**Update:** Can confirm even after a fresh complete reinstall of Kodi and Seren, this is indeed an issue and wasn't fixed by reinstall.

**Comment by jokerchyld** [comment] 2021-07-05 00:48
Commenting here just in case this is the same problem I am having.  If not, please move to new issue.

1. Watch something in Seren
2. Go to 'Real-Debrid, Log-In, Torrents tab'
3. Movie just viewed in Seren is there

Expected Behavior:
Movies I watch in Seren should not be saved to my RD cloud (torrents tab).

**Comment by Nuklear92** [comment] 2021-07-05 01:00
Exactly the same thing I mean for this issue. It's happening for tv show episodes and movies. It only works fine when you're watching anything directly from **My Files**.

**Comment by Nuklear92** [comment] 2021-07-15 18:58
@drinfernoo don't forget about this issue for the next update. 😏

**Comment by drinfernoo** [comment] 2021-07-30 14:34
I've been testing this out for the better part of this morning, and the only thing I see happening is that it looks like RD is actually doing this for us now. Every single link I play, I can see it get added to my account, and then removed again, before Seren even has the chance to call the "delete" endpoint.

**Comment by drinfernoo** [comment] 2021-07-30 15:14
I think we've actually had this fixed in development for a bit now... Should be fine for the next update.

**Comment by jokerchyld** [comment] 2021-07-30 18:40
I just checked with Jungle Cruise. Still showing up in Torrents tab and not
removing. Assuming next update puts in the logic to make RD do it
automatically?

**Comment by drinfernoo** [comment] 2021-07-30 19:28
@jokerchyld Yes... that's what "should be fine for next update" was referring to, and why I've labeled the issue "Awaiting Update".

**Comment by drinfernoo** [comment] 2021-08-05 13:27
This one should now be fixed in 2.1.4. Would you confirm if it's working for you now?

**Closed** 2021-08-05 14:31 UTC
Labels: bug
