### ISSUE TITLE
[REQUEST] 3 Requests

### ISSUE THREAD

**Issue by rizreflects** [nixgates/plugin.video.seren#665] opened 2021-08-07 21:21 UTC
The first request I have is regarding the default theme for serens source select. The writing is very small and certain people in my family struggle to read it due to eyesight problems. This is not an issue with other addons such as venom or fen because they display tags such as 'HDR' or 'REMUX' in big writing which is easy to read. I understand that it is possible to install themes for seren, but these themes are limited to skins which i no longer use (arctic horizon etc). Furthermore, Serens source select does look quite outdated compared to the alternative addons. It's not super important, but it would be nice if things such as posters and clear art were present when choosing a source (like venom for example).

My second request is to add an option to filter out dolby vision sources.

Finally, it would be great if there was an option to filter HDR items to the top of the list of sources. Currently, if an SDR link is larger in size it will automatically be chosen by seren. However it would be better if HDR links were put above SDR links even if the file size is smaller.

Thanks for all your work as usual. Greatly appreciated.

**Comment by drinfernoo** [comment] 2021-08-07 22:23
For your first request: This is exactly what the ability to use custom themes is *for*. Unfortunately, font sizes are basically **the** hardest thing to handle in custom windows, as almost every skin uses a different font. Likely the only thing you need to change to make a theme work, with your skin of choice, is the font. However, no matter what we change the "stock" font to, somebody on a different skin will end up having this issue again in the future, for the same reason.

For your second request: Duplicate of #533.

For your third request: Sure, it's possible to get a sorting option for HDR. We're hoping to look into sorting and filtering for a future update.

**Closed** 2021-08-08 01:42 UTC
Labels: enhancement
