### ISSUE TITLE
[BUG] Smart Play select of close does not close the playlist

### ISSUE THREAD

**Issue by streamindemons** [nixgates/plugin.video.seren#446] opened 2021-01-20 03:07 UTC
https://paste.kodi.tv/simazinafa

The Smart Play Dialog still plays an episode after hitting "close" or "cancel" (dependent on skin)

1. Go to any episode that will have a following episode after it (shuffle play works too)
2. Scroll to the last 45 seconds or so when the dialog pops upo
3. Hit "close"
4. show will finish and go into next episode instead of closing out of the playlist

**Expected behavior**
The next episode does not play and you are back to the home page

Kodi 18.9
 Seren 2.0.13

**Comment by nixgates** [comment] 2021-01-20 05:48
@streamindemons this is by design, that dialog will either skip to next or close itself depending on the button selected.

This is why in the original skin, it is labeled as "Close" and not cancel.

**Closed by nixgates** 2021-01-20 05:48 UTC
Labels: bug

**Comment by drinfernoo** [comment] 2021-01-21 01:25
Could we have the option to override Smart Play, stopping early?

This would basically be "play now", "play next", or "stop".

**Comment by inb4after** [comment] 2021-01-21 09:03
Adding this here for future reference, above isn't a bug, more like an alteration/feature request.

I think this is how it should be, with minimal new features added. 

https://i.imgur.com/9RK89o2

The only thing that doesn't happen for both sides is pause at end, not sure where to put that when smart play is disabled.
