### ISSUE TITLE
 video resume not working on TV shows

### ISSUE THREAD

**Issue by hishamaltmimy** [nixgates/plugin.video.seren#714] opened 2021-11-08 09:29 UTC
Hello my friend why is the video resume not working on TV shows

**Comment by hishamaltmimy** [comment] 2021-11-08 11:10
https://paste.kodi.tv/kesatutuge

**Comment by drinfernoo** [comment] 2021-11-16 15:23
Duplicate of #706.

**Closed** 2021-11-16 15:24 UTC
Labels: bug, duplicate
