### ISSUE TITLE
[BUG] Seren 2.2.2 doesn’t mark episodes as Watched in Trakt

### ISSUE THREAD

**Issue by eengert** [nixgates/plugin.video.seren#831] opened 2022-10-30 20:40 UTC
**Describe the bug**
Since updating to Seren 2.2.2 episodes are no longer being marked as Watched in Trakt, even after Re-authorizing. 

**To Reproduce**
1. Watch an episode using Seren 2.2.2
2. After completing the episode, check Trakt and notice that the episode has not been marked as Watched. 

**Expected behavior**
Episode should be marked as Watched in Trakt. 

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi 19.4
 - Seren 2.2.2

**Additional context**
This functionality worked fine in previous versions of Seren.

**Comment by TapMeDead** [comment] 2022-10-31 00:17
I can second this, been happening for a day or two

**Comment by drinfernoo** [comment] 2022-10-31 18:42
Closing as duplicate of #829.

**Closed** 2022-10-31 18:42 UTC
Labels: bug, duplicate
