### ISSUE TITLE
[BUG] Plugin url path missing trailing / for widgets back navigation

### ISSUE THREAD

**Issue by arcsur** [nixgates/plugin.video.seren#299] opened 2021-01-03 08:41 UTC
When integrating with widgets, the path does not have a trailing slash after plugin://plugin.video.seren action path.  This causes issues with Kodi knowing how to go back.  Without the trailing / it goes to the previous screen within seren plugin and not the actual previous screen.

This issue is very apparent when using script.skinshortcuts which is integrated with many skins.  The back button does not go back to the prior screen but instead goes to the prior screen in seren addon.

The path produced when browsing the plugin with a skin using script.skinshortcuts will produce something similar to:
`plugin://plugin.video.seren?action=showGenresGet&action_args=action&from_widget=true`
Instead of a path which would allow a proper back function similar to the following:
`plugin://plugin.video.seren/?action=showGenresGet&action_args=action&from_widget=true`

Looking at the code, you already do widget detection, I would propose the following change which works without error in my testing inside modules/globals.py create_url function:

```
    def create_url(self, base_url, params):
        if params is None:
            return base_url
        if "action_args" in params and isinstance(params["action_args"], dict):
            params["action_args"] = json.dumps(params["action_args"], sort_keys=True)
        params["from_widget"] = "true" if not self.is_addon_visible() else "false"
        sep = "/" if not self.is_addon_visible() else ""
        return "{}{}?{}".format(base_url, sep, tools.urlencode(sorted(params.items())))
```

This change simply adds the path separator if this is from a widget which allows widget path back path to work correctly whilst avoiding filling the logs full of errors for inputstream adaptive path errors.

**Comment by nixgates** [comment] 2021-01-04 03:31
Duplicate of issue #298 closing.

Please reference the above issue for further discussion

**Closed by nixgates** 2021-01-04 03:31 UTC
Labels: bug
