### ISSUE TITLE
[BUG] Beckup to open wizard  inc log 

### ISSUE THREAD

**Issue by tomtomclub** [nixgates/plugin.video.seren#367] opened 2021-01-06 22:31 UTC
Kodi 18.9 Android  
Systeem shield pro 
Addon: seren /dev/Nixgates
2.0.10
 Wen I  backup kodi  build  (open wizard) and install  build again  the ,
Seren ,addon in de build is gone. The  Log shows problem  Catch module name
https://paste.kodi.tv/kanavurabu

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by LoganWolverineX** [comment] 2021-01-07 01:48
Yea this is the bug from #290 .  For now, you'll need to just re-install seren add-on over the add-on without uninstalling it after openwizard restores the build.  All settings are preserved.

**Comment by nixgates** [comment] 2021-01-07 05:56
@tomtomclub howdy as Logan mentioned we do have a ticket open for this already so I'm going to close this as a duplicate.

I'm not entirely certain as of yet if this caused by Seren yet but it will get looked at eventually :)

**Closed** 2021-01-07 05:56 UTC
Labels: bug, duplicate
