### ISSUE TITLE
Dolby Vision filter - Feature request 

### ISSUE THREAD

**Issue by TheLiquidChef** [nixgates/plugin.video.seren#722] opened 2021-12-08 06:53 UTC
Please can we have the option to filter out Dolby Vision content. It doesn’t display correctly on various Kodi setups so would be nice to have this feature. 

I’ve currently added the following lines to my source_utils.py file under the Undesirable Items filter which seems to do the trick:

" dv ", "dovi", "dolby vision", "dolbyvision"

It would be nice if we could get this feature implemented natively in Seren as we currently have to re-add these filters after each update.

On a side note, I just wanted to thank the devs for this epic add on.

**Comment by drinfernoo** [comment] 2021-12-08 12:34
Duplicate of #533.

**Closed** 2021-12-08 12:34 UTC
Labels: duplicate
