### ISSUE TITLE
Seren and Trakt

### ISSUE THREAD

**Issue by moorscoin** [nixgates/plugin.video.seren#40] opened 2019-02-09 05:14 UTC
Noticed that when i start watching a show from next up and i stop the show about 10 mins in, it gets marked as watched when i try to go back to it.   Kodi 18 seren 1.29 up next installed as well.

**Comment by drinfernoo** [comment] 2019-02-09 19:17
Duplicate of #37.

**Closed** 2019-02-11 03:56 UTC
