### ISSUE TITLE
[BUG] Next up thumbnail replaces background

### ISSUE THREAD

**Issue by inky-pits** [nixgates/plugin.video.seren#493] opened 2021-01-30 11:27 UTC
**Logs**

https://paste.kodi.tv/oqidosoxeq

Edit: After disabling episode fanart in artwork advanced settings the Next up section now displays as expected. 

Nvidia Shield TV, Kodi 18.9, Seren 2.0.16
Estuary skin, Movie/Show view: Wall, season/episode: wide view. Fanart key entered, advanced artwork enabled, artwork settings on their defaults.

 In the Next up episode list at first there is background artwork and a poster rather than thumbnail on the left-hand side above the synopsis. However after watching an episode, the next episode will have a thumbnail above it synopsis and the thumbnail is used for the background which can look quite stretched. I've tried clearing Trakt metadata in Seren Trakt tools and Kodi thumbnail folder contents before rebooting but the issue remains.

The expected behaviour was TV Show background artwork and a episode thumbnail on the left-hand side above the synopsis.

![IMG_20210130_112602](https://user-images.githubusercontent.com/78259034/106355135-0e80e980-62ee-11eb-8b23-d05133556292.jpg)
![IMG_20210130_112619](https://user-images.githubusercontent.com/78259034/106355142-15a7f780-62ee-11eb-9077-dcbdcdbcb08a.jpg)

**Comment by nixgates** [comment] 2021-02-01 04:53
@inky-pits hey this looks to be a duplicate of issue #330 (note, that issue affects more lists than just the one in the title)

**Closed** 2021-02-01 04:54 UTC
Labels: bug
